---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 進階搜尋技術可協助您找到所需的資產。 
keywords: asset page, objects, search, advanced, alerts 
---
= 搜尋資產與警示的提示與秘訣
:allow-uri-read: 


[role="lead"]
您可以使用多種搜尋技術來搜尋監控環境中的資料或物件。

* *通配符搜尋*
+
您可以使用*字元執行多個字元的萬用字元搜尋。例如、_applic* n_會傳回_application_。

* *用於搜尋的詞彙*
+
片語是一組字詞、以雙引號括住、例如「VNX LUN 5」。您可以使用雙引號來搜尋名稱或屬性中含有空格的文件。

* *布林運算子*
+
您可以使用布林運算子或、及（而非）合併多個字詞、以形成更複雜的查詢。

+
或

+
OR運算子是預設的聯合運算子。

+
如果兩個詞彙之間沒有布林運算子、則會使用OR運算子。

+
OR運算子會連結兩個詞彙、如果文件中有任一詞彙、就會找到相符的文件。

+
例如、_storage或NetApp_會搜尋包含_storage或_NetApp_的文件。

+
對於符合大部分條款的文件、會給予高分。

+
和

+
您可以使用AND運算子來尋找單一文件中同時存在兩個搜尋字詞的文件。例如、_storage和NetApp_會搜尋同時包含_storage和_NetApp_的文件。

+
您可以使用符號「*&&*」、而非「and」這個字。

+
不是

+
當您使用Not運算子時、搜尋結果中會排除所有包含「Not」字詞之後的文件。例如、_storage而非NetApp_會搜尋僅包含_storage的文件、而非_NetApp_的文件。

+
您可以使用符號*！*取代非。



搜尋不區分大小寫。



== 使用索引詞彙進行搜尋

符合更多索引詞彙的搜尋結果會獲得較高的分數。

搜尋字串會依空格分割成不同的搜尋字詞。例如、搜尋字串「storage aurora NetApp」會分割成三個關鍵字：「storage」、「aurora」和「NetApp」。搜尋是使用這三個詞彙來執行。大部分符合這些詞彙的文件將獲得最高分數。您提供的資訊越多、搜尋結果就越好。例如、您可以依儲存設備的名稱和型號來搜尋儲存設備。

UI會顯示各類別的搜尋結果、每個類別的結果最多三項。如果您找不到所需的物件、可以在搜尋字串中加入更多字詞、以改善搜尋結果。

下表提供可新增至搜尋字串的索引詞彙清單。

|===
| 類別 | 索引詞彙 


| 儲存設備 | 「儲存設備」名稱廠商模式 


| StoragePool | 所有相關磁碟之所有相關內部磁碟區名稱之儲存設備廠商儲存模型名稱之儲存設備序號的儲存IP位址名稱 


| 內部Volume | 儲存設備廠商儲存模式之儲存設備序號儲存設備IP位址的「內部磁碟區」名稱、其儲存資源池名稱為所有相關應用程式的所有相關共用名稱 


| Volume | 「Volume」名稱標籤名稱儲存設備廠商儲存模型儲存設備序號之儲存設備IP位址的儲存資源池名稱、其所有內部磁碟區名稱 


| 儲存節點 | 儲存設備廠商儲存模式儲存設備序號之儲存設備IP位址的「StorageNode」名稱 


| 主機 | 「主機」名稱IP位址所有相關應用程式的名稱 


| 資料存放區 | 「資料存放區」會將所有內部磁碟區的所有磁碟區名稱命名為虛擬中心IP名稱 


| 虛擬機器 | 「虛擬機器」名稱DNS名稱IP位址所有相關應用程式資料存放區名稱主機名稱的主機IP位址名稱 


| 交換器（一般和NPV） | 「交換器」IP位址WWN名稱序號架構的網路WWN網域ID名稱 


| 應用程式 | 「應用程式」名稱租戶業務單位專案 


| 磁帶 | 「磁帶」IP位址名稱序號廠商 


| 連接埠 | 「連接埠」WWN名稱 


| 網路 | 「Fabric」WWN名稱 


| 儲存虛擬機器（SVM） | 「storagevirtualmachine」名稱UUID 
|===