---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 您可以在 Cloud Volumes ONTAP 一個還原系統上啟動一次寫入、多次讀取（ WORM ）儲存、以未修改的形式保留檔案、保留指定的保留期間。Cloud WORM儲存設備採用SnapLock 支援各種技術、這表示WORM檔案在檔案層級受到保護。 
---
= WORM 儲存設備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在 Cloud Volumes ONTAP 一個還原系統上啟動一次寫入、多次讀取（ WORM ）儲存、以未修改的形式保留檔案、保留指定的保留期間。Cloud WORM儲存設備採用SnapLock 支援各種技術、這表示WORM檔案在檔案層級受到保護。



== WORM儲存設備的運作方式

一旦檔案已提交至WORM儲存設備、即使保留期間已過、也無法修改。防竄改時鐘可決定 WORM 檔案的保留期間何時結束。

保留期間結束後、您必須負責刪除不再需要的任何檔案。



== 充電

WORM儲存設備的充電時數是每小時一次、視WORM磁碟區的總配置容量而定。

僅適用於 PAYGO 或年度承諾條款、 WORM 授權可透過雲端供應商的市場購買。WORM 支援節點型和容量型授權模式。


NOTE: BYOL 授權不適用於 Cloud Volumes ONTAP 上的 WORM 儲存設備。

您應該瞭解Cloud Volumes ONTAP 下列使用支援功能的充電行為：

* 從ONTAP S59.10.1開始、WORM磁碟區和非WORM磁碟區可以存在於同一個集合體上。
* 如果您在建立Cloud Volumes ONTAP 一個功能不全的環境時啟用WORM、那麼您從BlueXP建立的每個磁碟區都會啟用WORM。不過ONTAP 、您可以使用「功能性CLI」或「系統管理程式」來建立已停用WORM的磁碟區。這些磁碟區不會以WORM速率收費。
* 如果您在建立工作環境時未啟用WORM、則從BlueXP建立的每個Volume都會停用WORM。這些磁碟區不會以WORM速率收費。


https://cloud.netapp.com/pricing["瞭解WORM儲存設備的定價"^]



== 啟動 WORM 儲存設備

如何啟動WORM儲存取決於Cloud Volumes ONTAP 您所使用的版本。



=== 9.10.1版及更新版本

從功能部件支援的版本起、您可以選擇在Volume層級啟用或停用WORM Cloud Volumes ONTAP 。

當您建立Cloud Volumes ONTAP 全新的支援環境時、系統會提示您啟用或停用WORM儲存設備：

* 如果您在建立工作環境時啟用WORM儲存、則您從BlueXP建立的每個Volume都會啟用WORM。但您可以使用System Manager或CLI來建立已停用WORM的磁碟區。
* 如果您在建立工作環境時停用WORM儲存設備、則從BlueXP、System Manager或CLI建立的每個Volume都會停用WORM。如果您想要在Cloud Volumes ONTAP 建立期間未啟用的支援環境中啟用WORM、您必須建立支援票證、並提供NetApp支援以取得協助。


無論選擇哪一項、您都應該這樣做 <<充電,瞭解充電的運作方式>>。



=== 9.10.0版及更早版本

您可以在 Cloud Volumes ONTAP 建立新的工作環境時、在一個可靠的系統上啟動 WORM 儲存設備。您從BlueXP建立的每個磁碟區都已啟用WORM。您無法停用個別磁碟區上的WORM儲存設備。



== 將檔案提交至 WORM

您可以使用應用程式、透過 NFS 或 CIFS 將檔案提交至 WORM 、或使用 ONTAP CLI 自動將檔案自動提交至 WORM 。您也可以使用 WORM 可應用檔案來保留遞增寫入的資料、例如記錄資訊。

在 Cloud Volumes ONTAP 啟用 WORM 儲存設備之後、您必須使用 ONTAP CLI 來管理 WORM 儲存設備。如需相關指示、請參閱 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["本文檔 ONTAP"^]。



== 刪除 WORM 檔案

您可以在保留期間使用權限刪除功能刪除 WORM 檔案。

如需相關指示、請參閱 https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["本文檔 ONTAP"^]



== WORM與資料分層

當您建立全新Cloud Volumes ONTAP 的版本的更新版本時、可以同時啟用資料分層和WORM儲存。利用WORM儲存設備進行資料分層、可將資料分層至雲端的物件存放區。

您應該瞭解下列關於啟用資料分層和WORM儲存設備的資訊：

* 分層至物件儲存的資料不含ONTAP 「支援WORM」功能。為了確保端點對端點WORM功能、您必須正確設定儲存區權限。
* 分層至物件儲存的資料並不具備WORM功能、這意味著從技術上而言、任何擁有完整儲存區和容器存取權的人、都能移除由ONTAP 實物分級的物件。
* 啟用WORM和分層後、將Cloud Volumes ONTAP 會封鎖還原或降級至物件9.8。




== 限制

* WORM儲存在Cloud Volumes ONTAP 「受信任的儲存管理員」模式下運作。儘管WORM檔案受到保護、不會遭到竄改或修改、但即使這些磁碟區包含未過期的WORM資料、叢集管理員仍可刪除這些磁碟區。
* 除了值得信賴的儲存管理員模式之外Cloud Volumes ONTAP 、在「值得信賴的雲端管理員」模式下、WORM儲存設備也會以隱含方式運作。雲端管理員可以直接從雲端供應商移除或編輯雲端儲存設備、在WORM資料到期日前刪除。

