---
sidebar: sidebar 
permalink: concept_forensic.html 
keywords: Forensic, user, entity, community 
summary: 鑑識總覽 
---
= 鑑識資訊
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:history: Review 1/17,
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
取證檢視可讓您存取使用者、實體、社群和使用者活動資訊。



== 檢查使用者資訊

按一下*取證>使用者*以存取使用者檢視。

此檢視顯示一般使用者資訊：

* 使用者名稱、並提供使用者詳細資訊的連結。
* 使用者活動所引發的警示
* 使用者所在的社群數量、以及社群頁面的連結
* 使用者位置
* 使用者上次存取的實體


按一下使用者名稱、即可在中存取更多詳細資訊 link:forensic_user_detail.html["使用者總覽"]



== 檢查實體資訊

按一下「*鑑識」>「實體*」以存取「實體」檢視。

本頁顯示使用者存取實體的一般資訊：

詳細說明包括：

* 實體名稱
* 實體類型


* 與實體的社群關係
* 實體路徑
* 上次存取時間
* 實體大小


按一下「實體名稱」以存取中的詳細資訊 link:forensic_entity_detail.html["實體總覽"]

按一下「社群」數以顯示包含該實體的社群。



== 檢查社群資訊

按一下「*取證>社群*」以存取「社群」頁面。

此檢視提供：

* 社群名稱
* 社群相關警示
* 社群的使用者數
* 社群的實體數不清


按一下或搜尋社群名稱、即可存取「社群詳細資料」頁面。

社群設定檔:: 列出社群使用者所在位置和其他最近的社群。
社群行為:: 顯示存取的實體數量、並顯示讀取、寫入和中繼資料存取作業。
使用者與實體:: 識別社群中的使用者總數和實體總數。
社群分析::
+
--
* 社群使用者趨勢
* 在實體上執行的作業
* 警示趨勢


--


按一下社群名稱、即可在中存取更多詳細資訊 link:forensic_community_detail.html["社群詳細資料"]



== 檢查使用者活動資訊

按一下「*鑑識」>「使用者活動*」以存取「使用者活動」檢視。

對於每個受監控的使用者、此檢視說明：

* 實體存取時間
* 使用者以使用者總覽連結存取實體
* 執行活動：
+
** 讀取
** 寫入
** 建立
** 重新命名


* 實體路徑
* 實體類型
* 存取位置按一下使用者名稱、即可在中存取更多詳細資訊 link:forensic_user_detail.html["實體詳細資料"]

