---
sidebar: sidebar 
permalink: concept-overview-cvo.html 
keywords: what is cloud volumes ontap, cloud volumes ontap features, features, cloud volumes ontap overview, overview of cloud volumes ontap, cloud backup, cloud data sense 
summary: 利用 NetApp 技術、您可以最佳化雲端儲存成本與效能、同時強化資料保護、安全性與法規遵循。 Cloud Volumes ONTAP 
---
= 深入瞭解 Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
利用 NetApp 技術、您可以最佳化雲端儲存成本與效能、同時強化資料保護、安全性與法規遵循。 Cloud Volumes ONTAP

不只是軟體的儲存應用裝置、可在雲端上執行功能完善的資料管理軟體。 Cloud Volumes ONTAP ONTAP它提供企業級儲存設備、具備下列主要功能：

* 儲存效率
+
運用內建的重複資料刪除技術、資料壓縮、精簡配置及複製技術、將儲存成本降至最低。

* 高可用度
+
確保雲端環境發生故障時、企業的可靠性和持續營運。

* 資料保護
+
利用 NetApp 領先業界的複寫技術 SnapMirror 、將內部部署資料複寫到雲端、讓次要複本可輕鬆用於多種使用案例。 Cloud Volumes ONTAP

+
Cloud Volumes ONTAP 也與 BlueXP 備份與還原整合、提供保護的備份與還原功能、以及雲端資料的長期歸檔。

+
link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["深入瞭解 BlueXP 備份與還原"^]

* 資料分層
+
在高效能與低效能儲存資源池之間隨需切換、而不需將應用程式離線。

* 應用程式一致性
+
使用 NetApp SnapCenter 功能確保 NetApp Snapshot 複本的一致性。

+
https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["深入瞭SnapCenter 解功能"^]

* 資料安全
+
支援資料加密、並提供防範病毒和勒索軟體的功能。 Cloud Volumes ONTAP

* 隱私權法規遵循控管
+
與 BlueXP 分類整合可協助您瞭解資料內容並識別敏感資料。

+
https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["深入瞭解 BlueXP 分類"^]




NOTE: 不含適用於功能的授權 ONTAP 。 Cloud Volumes ONTAP

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["檢視支援 Cloud Volumes ONTAP 的支援的支援功能"^]

https://cloud.netapp.com/ontap-cloud["深入瞭 Cloud Volumes ONTAP 解功能"^]
