---
sidebar: sidebar 
permalink: concept-active-iq.html 
keywords: autosupport, active iq, digital advisor, active iq digital advisor, telemetry 
summary: 這個功能的元件會收集遙測資料並傳送給分析人員。AutoSupport ONTAPActive IQ Digital Advisor 會分析來自 AutoSupport 的資料，並提供主動式防護與最佳化功能。利用人工智慧、Active IQ 即可識別潛在問題、並在問題影響企業之前協助您解決問題。 
---
= AutoSupport 與 Active IQ Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
這個功能的元件會收集遙測資料並傳送給分析人員。AutoSupport ONTAPActive IQ Digital Advisor 會分析來自 AutoSupport 的資料，並提供主動式防護與最佳化功能。利用人工智慧、Active IQ 即可識別潛在問題、並在問題影響企業之前協助您解決問題。轉換測試變更。

本地化變更：啟用 docbot 和測試 locT 顯示。測試 docbot 停用功能。測試 ruby 升級。

透過雲端型入口網站和行動應用程式、提供可據以行動的預測分析和主動式支援、讓您能夠在全球混合雲中最佳化資料基礎架構。Active IQ所有擁有有效的NetApp客戶都能從NetApp獲得資料導向的見解和建議Active IQ （功能因產品和支援層而異）SupportEdge 。

以下是Active IQ 您可以利用下列功能來執行的作業：

* 規劃升級。
+
可識別環境中的問題、這些問題可透過升級至更新版本的VMware知識來解決、而升級顧問元件則可協助您規劃成功的升級方案。Active IQ ONTAP

* 檢視系統健全狀況。
+
您的「不健全狀況」儀表板會回報任何問題、並協助您修正這些問題。Active IQ監控系統容量、確保儲存空間永遠不會耗盡。檢視系統的支援案例。

* 管理效能：
+
顯示系統效能的時間比您在《VMware系統管理程式》中看到的更長。Active IQ ONTAP找出影響您效能的組態和系統問題。
最大化效率。檢視儲存效率指標、找出在更少空間中儲存更多資料的方法。

* 檢視庫存與組態。
+
顯示完整的庫存、軟體和硬體組態資訊。Active IQ查看服務合約何時到期並續約、以確保您仍享有支援。



.相關資訊
* https://docs.netapp.com/us-en/active-iq/["NetApp 文件：Active IQ Digital Advisor"^]
* https://aiq.netapp.com/custom-dashboard/search["產品Active IQ 發表"^]
* https://www.netapp.com/us/services/support-edge.aspx["部門服務SupportEdge"^]

