---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, cloud manager 
summary: BlueXP提供Cloud Volumes ONTAP 簡化且進階的功能、可管理各種不支援的儲存設備。 
---
= 儲存管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP提供Cloud Volumes ONTAP 簡化且進階的功能、可管理各種不支援的儲存設備。


CAUTION: 所有磁碟和集合體都必須直接從BlueXP建立和刪除。您不應從其他管理工具執行這些動作。這樣做可能會影響系統穩定性、阻礙未來新增磁碟的能力、並可能產生備援雲端供應商費用。



== 儲存資源配置

BlueXP Cloud Volumes ONTAP 可讓您購買磁碟並管理Aggregate、輕鬆配置資料以利執行功能。您只需建立磁碟區即可。如果需要、您可以使用進階分配選項自行配置集合體。



=== 簡化資源配置

Aggregate 可為磁碟區提供雲端儲存設備。當您啟動執行個體、以及配置其他Volume時、BlueXP會為您建立Aggregate。

建立磁碟區時、BlueXP會執行以下三項操作之一：

* 它會將磁碟區放置在現有的 Aggregate 上、該集合體具有足夠的可用空間。
* 它會為現有的 Aggregate 購買更多磁碟、將磁碟區放在現有的 Aggregate 上。


ifdef::aws[]

+
如果 AWS 中支援彈性磁碟區的集合體、 BlueXP 也會增加 RAID 群組中磁碟的大小。 link:concept-aws-elastic-volumes.html["深入瞭解彈性磁碟區的支援"]。

endif::aws[]

* 它會為新的 Aggregate 購買磁碟、並將該磁碟區放在該 Aggregate 上。


BlueXP會根據以下幾項因素來決定新磁碟區的放置位置：Aggregate的最大大小、是否啟用精簡配置、以及Aggregate的可用空間臨界值。


TIP: 帳戶管理員可從 * 設定 * 頁面修改可用空間臨界值。

ifdef::aws[]



==== AWS 中集合體的磁碟大小選擇

當BlueXP在Cloud Volumes ONTAP AWS中建立新的Aggregate以供其使用時、它會隨著系統中的Aggregate數量增加、逐漸增加集合體中的磁碟大小。這樣做是為了確保您可以在系統達到AWS允許的最大資料磁碟數量之前、先使用系統的最大容量。

例如、BlueXP可能會選擇下列磁碟大小：

[cols="3*"]
|===
| Aggregate 編號 | 磁碟大小 | 最大 Aggregate 容量 


| 1. | 500 GiB | 3 等級 


| 4. | 1 TiB | 6 TiB 


| 6. | 2 TiB | 12 TiB 
|===

NOTE: 此行為不適用於支援Amazon EBS彈性磁碟區功能的集合體。啟用彈性磁碟區的集合體由一或兩個RAID群組組成。每個RAID群組都有四個容量相同的磁碟。 link:concept-aws-elastic-volumes.html["深入瞭解彈性磁碟區的支援"]。

您可以使用進階配置選項自行選擇磁碟大小。

endif::aws[]



=== 進階分配

您可以自行管理Aggregate、而非讓BlueXP為您管理Aggregate。 link:task-create-aggregates.html["從 * 進階分配 * 頁面"]、您可以建立新的集合體、包括特定數量的磁碟、新增磁碟至現有的集合體、以及在特定的集合體中建立磁碟區。



== 容量管理

客戶管理員可以選擇是否要由BlueXP通知您儲存容量決策、或是由BlueXP自動管理您的容量需求。

此行為由連接器上的_Capacity Management Mode_決定。容量管理模式會影響Cloud Volumes ONTAP 由該Connector管理的所有不完整系統。如果您有另一個Connector、則可以以不同的方式設定。



=== 自動容量管理

容量管理模式預設為自動。在此模式中、當Cloud Volumes ONTAP 需要更多容量時、BlueXP會自動購買新的磁碟以供執行個體使用、刪除未使用的磁碟集合（Aggregate）、視需要在Aggregate之間移動磁碟區、以及嘗試取消故障磁碟。

下列範例說明此模式的運作方式：

* 如果某個Aggregate達到容量臨界值、而且有空間容納更多磁碟、則BlueXP會自動為該Aggregate購買新的磁碟、讓磁碟區持續成長。
+
BlueXP每15分鐘檢查一次可用空間比率、以判斷是否需要購買額外的磁碟。



ifdef::aws[]

+
如果 AWS 中支援彈性磁碟區的集合體、 BlueXP 也會增加 RAID 群組中磁碟的大小。 link:concept-aws-elastic-volumes.html["深入瞭解彈性磁碟區的支援"]。

endif::aws[]

* 如果Aggregate達到容量臨界值、但無法支援任何其他磁碟、則BlueXP會自動將磁碟區從該Aggregate移至具有可用容量的Aggregate、或移至新的Aggregate。
+
如果BlueXP為磁碟區建立新的Aggregate、則會選擇適合該磁碟區大小的磁碟大小。

+
請注意、可用空間現在可在原始 Aggregate 上使用。現有磁碟區或新磁碟區可以使用該空間。在此案例中、無法將空間傳回雲端產品。

* 如果Aggregate不包含超過12小時的磁碟區、則BlueXP會將其刪除。




==== 利用自動容量管理來管理 LUN

BlueXP的自動容量管理不適用於LUN。當BlueXP建立LUN時、會停用自動擴充功能。



=== 手動容量管理

如果帳戶管理員將容量管理模式設為手動、則必須決定容量時、BlueXP會顯示必要行動訊息。自動模式中所述的相同範例適用於手動模式、但您必須接受這些動作。



=== 深入瞭解

link:task-manage-capacity-settings.html["瞭解如何修改容量管理模式"]。
