---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 支援強大的API、可與其他應用程式（例如CMDB）整合。Cloud Secure 
---
= 部分API Cloud Secure
:allow-uri-read: 


[role="lead"]
利用此解決方案、NetApp客戶和獨立軟體廠商（ISV）能夠將支援功能與其他應用程式（例如CMDB或其他票務系統）整合。Cloud Secure Cloud Secure

API存取需求：

* API存取權杖模式用於授予存取權。
* API Token管理是Cloud Secure 由具備管理員角色的使用者執行。




== API文件（Swagger）

您可以登入Cloud Secure 到「介紹」並瀏覽至「*管理> API存取*」、以找到最新的API資訊。按一下「* API Documentation *（* API文件*）」連結。API文件是以Swagger為基礎、提供API的簡短說明與使用資訊、並可讓您在環境中試用。



== API存取權杖

在使用Cloud Secure 此功能之前、您必須先建立一個或多個* API存取權杖*。存取權杖可授予讀取權限。您也可以設定每個存取權杖的到期日。

若要建立存取權杖：

* 按一下「*管理> API存取*」
* 按一下「*+ API存取權杖*」
* 輸入* Token Name*
* 指定*權杖過期*



NOTE: 您的權杖只能在建立程序期間複製到剪貼簿並儲存。建立權杖之後、就無法擷取這些權杖、因此強烈建議您複製權杖、並將其儲存在安全的位置。系統會提示您按一下「複製API存取權杖」按鈕、然後再關閉權杖建立畫面。

您可以停用、啟用及撤銷權杖。停用的權杖可以啟用。

權杖可從客戶的觀點授予API一般用途存取權限、以管理其本身環境範圍內的API存取。

應用程式會在使用者成功驗證及授權存取後、收到存取權杖、然後在呼叫目標API時、將存取權杖作為認證。傳遞的權杖會通知API、該權杖的承載器已獲授權存取API、並根據授權期間授予的範圍執行特定動作。

傳遞存取權杖的HTTP標頭為* X-CloudInsights：Apikes*

例如、使用下列項目來擷取儲存資產：

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
其中、_<API_Access_Token >>是您在API存取金鑰建立期間所儲存的權杖。

如需詳細資訊、請參閱「*管理> API存取*」下的「_API文件_」連結。
