---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: 資產頁面的「使用者資料」區段可讓您將註釋或應用程式指派給目前資產。 
keywords: asset page, user data, applications, annotations 
---
= 使用者資料區段
:allow-uri-read: 


[role="lead"]
資產頁面的「使用者資料」區段隨即顯示、並可讓您變更任何使用者定義的資料、例如應用程式和註釋。



== 使用「使用者資料」區段來指派或修改應用程式

您可以將環境中執行的應用程式指派給特定資產（主機、虛擬機器、磁碟區、內部磁碟區、qtree、 和Hypervisor）。「使用者資料」區段可讓您新增、變更或移除指派給資產的應用程式。除了Volume以外、所有這些資產類型都可以指派多個應用程式。

.步驟
. 執行下列任一動作、找出資產頁面：
+
.. 查詢資產清單、然後從清單中選取一個。
.. 在儀表板上找出資產名稱、然後按一下該名稱。
.. 執行搜尋並從結果中選擇資產。
+
隨即顯示「資產」頁面。頁面的「使用者資料」區段會顯示目前指派的應用程式或註釋。





若要變更指派的應用程式、或指派應用程式或其他應用程式、請下拉「*應用程式*」清單、然後選取您要指派給該資產的應用程式。您可以輸入以搜尋應用程式、或從清單中選取應用程式。

若要移除應用程式、請下拉應用程式清單、然後取消勾選應用程式。



== 使用「使用者資料」區段來指派或修改附註

自訂Cloud Insights 功能時、若要追蹤符合公司需求的資料、您可以定義稱為註釋的專屬附註、然後將其指派給您的資產。資產頁面的「使用者資料」區段會顯示指派給資產的附註、並可讓您變更指派給該資產的附註。

.步驟
. 若要新增資產附註、請在資產頁面的「使用者資料」區段中、按一下「*+附註*」。
. 從清單中選取註釋。
. 按一下「Value（值）」、然後根據所選的註釋類型執行下列任一動作：
+
.. 如果註釋類型為清單、日期或布林值、請從清單中選取一個值。
.. 如果註釋類型為文字、請輸入一個值。


. 按一下儲存。


註釋會指派給資產。您稍後可以使用查詢來篩選資產。

如果您要在指派註釋後變更其值、請下拉註釋清單、然後輸入不同的值。

如果註釋屬於清單類型、且已選取「在flly_上新增值」選項、則除了選取現有值之外、您也可以輸入新值。
