---
sidebar: sidebar 
permalink: io_density_nonroot.html 
keywords: notifications, annotations, queries, applications, 
summary: IO密度 
---
= 確保IO密度資料僅說明內部資料磁碟區
:allow-uri-read: 


[role="lead"]
在NetApp儲存系統中、根Aggregate包含根磁碟區、其中包含用於管理和控制儲存系統的特殊目錄和組態檔案。這些作業可能會在根集合體中產生大量活動。當您查詢Cloud Insights IO密度最高的前10大內部磁碟區時、您的結果可能包括NetApp根集合體為前10名的成員。

監控環境時、更重要的是判斷哪些內部資料磁碟區產生高I/O密度的數字。為了準確識別資料磁碟區、您必須將NetApp內部磁碟區與用來監控I/O密度的查詢區隔離開來。

本指南說明如何輕鬆識別NetApp根集合體、將其與內部Volume查詢結果區隔、以及建立規則、以在新增至系統時排除任何新的NetApp根集合體。下列功能可確保您的I/O密度報告是從內部資料磁碟區衍生而來。Cloud Insights

* 系統會建立一個查詢、以識別Cloud Insights 所有由NetApp監控的NetApp根集合體。
* 每個NetApp根集合體都會指派附註。
* 建立註釋規則以排除NetApp根Aggregate。




== 建立查詢以識別您環境中的NetApp根集合體

查詢可根據使用者選取的條件、提供精細的搜尋層級。使用查詢可讓您搜尋環境中包含NetApp根Aggregate的內部磁碟區。

.步驟
. 在本報告中Cloud Insights 、建立查詢以識別您環境中的NetApp根集合體：*查詢>+新查詢>儲存資源池*
. 輸入根Aggregate的名稱
+
此範例使用"aggr0"做為名稱。建立Aggregate時、只能遵循下列名稱需求：

+
** 必須以字母或底線開頭（_）。
** 它只能包含字母、數字和底線。
** 可以少於250個字元。




在大多數情況下、Aggr0、aggr_0或類似名稱。可能需要迭代程序來識別環境中的所有NetApp根集合體。

. 按一下「*儲存*」、然後輸入新查詢的名稱。
+
如前所述、這可能是一個迭代程序、需要多個查詢來識別所有NetApp根集合體。





== 為查詢傳回的根磁碟區建立附註

附註是您指派給資產的專屬附註、可讓您根據資產附註來篩選資產。您所建立的註釋將用於識別環境中的NetApp根集合體、並確保它們不會包含在IO密度最高的內部磁碟區清單中。

您必須已識別出要從「高I/O密度」報告中排除的所有根Aggregate。

.步驟
. 建立附註、以關聯您使用查詢所識別的所有NetApp根集合體：*管理>附註*
+
.. 輸入註釋名稱：* RootAggr*
.. 輸入註釋說明：*從「高I/O密度」清單中移除根Aggregate *
.. 輸入註釋類型：*布林*


. 按一下「*儲存*」




== 建立註釋規則、將特定Aggregate排除在I/O密度報告之外、予以自動化

您可以使用註釋規則、自動將註釋套用至多個資產、作為手動套用註釋至個別資產的替代方法。附註規則是根據您建立的查詢而定、當在系統上執行時、會將新資產新增至現有的資產集。當這些資產組合排除在納入範圍之外時、新資產也會自動排除在外。

您必須建立並儲存查詢、以識別您在環境中識別的NetApp根集合體。

.步驟
. 在功能表中、按一下*管理>註釋* Cloud Insights
. 按一下「*新增*」
. 請執行下列動作：
+
.. 在「名稱」方塊中、輸入描述規則* RootAggrExclud*的唯一名稱
.. 按一下「查詢」、然後選取Cloud Insights 「查詢」、以套用註釋規則至：* Aggregate0*
.. 按一下「註釋」、然後選取「*根目錄agg exclude *」
.. 按一下*值*並輸入*真*



