---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 使用報告撰寫工具來建立自訂（「ad -hoc」）報告 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= 建立自訂報告
:allow-uri-read: 


[role="lead"]
您可以使用報告撰寫工具來建立自訂報告。建立報告之後、您可以儲存報告並定期執行。報告結果可透過電子郵件自動傳送給您自己和其他人。


NOTE: 「報告」功能可在Cloud Insights 《資訊時報」中找到 link:concept_subscribing_to_cloud_insights.html["Premium Edition"]。

本節的範例說明下列程序、可用於Cloud Insights 任何一種「更新報告」資料模型：

* 找出要用報告回答的問題
* 判斷支援結果所需的資料
* 選取報告的資料元素


在設計自訂報告之前、您必須先完成一些必要的工作。如果您未完成這些作業、報告可能不準確或不完整。

例如、如果您未完成裝置識別程序、您的容量報告將不準確。或者、如果您尚未完成設定註釋（例如階層、業務單位和資料中心）、您的自訂報告可能無法準確報告整個網域的資料、或是某些資料點顯示「N/A」。

在您設計報告之前、請先完成下列工作：

* 全部設定 link:task_configure_data_collectors.html["資料收集器"] 正確。
* 在環境中的裝置和資源上輸入附註（例如階層、資料中心和業務單位）。在產生報告之前、讓註釋保持穩定是有益的、因為Cloud Insights 「消息報告」會收集歷史資訊。




=== 報告建立程序

建立自訂（也稱為「ad hoc」）報告的程序涉及數項工作：

* 規劃報告的結果。
* 識別資料以支援您的結果。
* 選取包含資料的資料模型（例如、調配資料模型、庫存資料模型等）。
* 選取報告的資料元素。
* 選擇性地格式化、排序及篩選報告結果。




==== 規劃自訂報告的結果

在您開啟報告撰寫工具之前、您可能會想要從報告中規劃所需的結果。使用報告撰寫工具、您可以輕鬆建立報告、而且可能不需要進行大量規劃；不過、您最好向報告申請者瞭解報告需求。

* 找出您要回答的確切問題。例如：
+
** 我還剩多少容量？
** 每個業務單位的計費成本為何？
** 各層級的容量為何、可確保業務單位在適當的儲存層級上一致？
** 如何預測電力和冷卻需求？（新增註釋至資源以新增自訂的中繼資料。）


* 找出您需要支援答案的資料元素。
* 找出您要在答案中看到的資料之間的關係。請勿在您的問題中加入不合邏輯的關係、例如「我想要查看與容量相關的連接埠」。
* 找出資料所需的任何計算方法。
* 判斷限制結果所需的篩選類型。
* 判斷您是否需要使用目前或歷史資料。
* 判斷您是否需要設定報告的存取權限、將資料限制在特定對象。
* 找出報告的發佈方式。例如、是否應以設定的排程寄送電子郵件、或是將其納入「團隊」內容資料夾區域？
* 判斷誰負責維護報告。這可能會影響設計的複雜度。
* 建立報告的圖樣。




==== 設計報告的秘訣

設計報告時、幾個秘訣可能會很有幫助。

* 判斷您是否需要使用目前或歷史資料。
+
大多數報告只需要回報Cloud Insights 有關更新資料的資訊。

* 提供容量與效能的歷史資訊、但不包括在庫存中。Cloud Insights
* 每個人都能看到所有資料、但您可能需要將資料限制在特定對象。
+
若要區隔不同使用者的資訊、您可以建立報告並設定其存取權限。





== 報告資料模型

包含數種資料模型、您可以從中選取預先定義的報告、或建立自己的自訂報告。Cloud Insights

每個資料模型都包含一個簡單的資料倉儲和一個進階的資料倉儲：

* 簡單的資料倉儲可讓您快速存取最常用的資料元素、並僅包含資料倉儲資料的最後一張快照、不含歷史資料。
* 進階資料倉儲可從簡單的資料倉儲中提供所有可用的值和詳細資料、並可存取歷史資料值。




=== 容量資料模型

可讓您回答有關儲存容量、檔案系統使用率、內部Volume容量、連接埠容量、qtree容量、 和虛擬機器（VM）容量。容量資料模型是多種容量資料模型的容器。您可以使用此資料模式建立報告、回答各種類型的問題：



=== 儲存與儲存資源池容量資料模型

可讓您回答有關儲存容量資源規劃的問題、包括儲存與儲存資源池、以及實體與虛擬儲存資源池資料。這種簡單的資料模式可協助您回答與現場容量有關的問題、以及隨著時間推移、各層級和資料中心的儲存資源池容量使用量。如果您是容量報告的新手、您應該從這種資料模型開始著手、因為它是更簡單、目標明確的資料模型。您可以使用此資料模型回答類似下列的問題：

* 達到80%實體儲存容量臨界值的預計日期為何？
* 特定層級陣列的實體儲存容量為何？
* 我的儲存容量是由製造商、產品系列以及資料中心提供？
* 所有層級陣列的儲存使用率趨勢為何？
* 使用率最高的前10大儲存系統為何？
* 儲存資源池的儲存使用率趨勢為何？
* 已配置多少容量？
* 哪些容量可供分配？




=== 檔案系統使用率資料模型

此資料模型可讓您在檔案系統層級查看主機的容量使用率。系統管理員可決定每個檔案系統的分配和使用容量、判斷檔案系統類型、並根據檔案系統類型識別趨勢統計資料。您可以使用此資料模型回答下列問題：

* 檔案系統的大小為何？
* 資料存放在何處、以及如何存取、例如本機或SAN？
* 檔案系統容量的歷史趨勢為何？因此、我們可以預期未來的需求為何？




=== 內部Volume容量資料模型

可讓您回答有關內部磁碟區已用容量、已分配容量及隨時間使用容量的問題：

* 哪些內部磁碟區的使用率高於預先定義的臨界值？
* 哪些內部磁碟區有可能因趨勢而耗盡容量？8我們內部磁碟區的使用容量與分配容量有何不同？




=== 連接埠容量資料模型

可讓您回答有關交換器連接埠連線、連接埠狀態和連接埠速度等問題。您可以回答下列類似問題、協助您規劃新交換器的採購方案：我該如何建立可預測資源（連接埠）可用度的連接埠使用量預測（根據資料中心、交換器廠商和連接埠速度）？

* 哪些連接埠可能會耗盡容量、提供資料速度、資料中心、廠商和主機與儲存連接埠數量？
* 隨著時間推移、交換器連接埠容量趨勢為何？
* 連接埠速度為何？
* 需要哪種類型的連接埠容量、以及哪個組織即將耗盡特定的連接埠類型或廠商？
* 購買該容量並提供該容量的最佳時機為何？




=== qtree容量資料模型

可讓您隨著時間而趨勢調整qtree使用率（使用量與分配容量等資料）。您可以依不同層級檢視資訊、例如依企業實體、應用程式、層級和服務層級。您可以使用此資料模型回答下列問題：

* qtree的使用容量與每個應用程式或企業實體設定的限制有何不同？
* 我們的使用量和可用容量有何趨勢、以便我們進行容量規劃？
* 哪些企業實體使用的容量最多？
* 哪些應用程式耗用的容量最多？




=== VM容量資料模型

可讓您報告虛擬環境及其容量使用量。此資料模型可讓您針對VM和資料儲存區的容量使用量隨時間變化提出報告。資料模型也提供精簡配置和虛擬機器計費資料。

* 如何根據虛擬機器和資料儲存區的資源配置來決定容量計費？
* 哪些容量未被VM使用、哪些部分未使用是可用的、孤立的或其他的？
* 根據消費趨勢、我們需要購買哪些產品？
* 我使用儲存精簡配置和重複資料刪除技術、可省下多少儲存效率？


VM容量資料模型中的容量是從虛擬磁碟（VMDK）取得。這表示使用VM容量資料模型的虛擬機器已配置大小是其虛擬磁碟的大小。這與Cloud Insights 在VMware View中的虛擬機器已配置容量不同、後者會顯示VM本身的已配置容量。



=== Volume容量資料模型

可讓您分析環境中磁碟區的所有層面、並依廠商、模型、層級、服務層級和資料中心來組織資料。

您可以檢視與孤立磁碟區、未使用的磁碟區和保護磁碟區（用於複寫）相關的容量。您也可以看到不同的Volume技術（iSCSI或FC）、並針對陣列虛擬化問題、將虛擬磁碟區與非虛擬磁碟區進行比較。

您可以使用此資料模型回答類似下列的問題：

* 哪些磁碟區的使用率高於預先定義的臨界值？
* 我的資料中心對於孤立Volume容量有何趨勢？
* 我的資料中心容量有多少是虛擬化或精簡配置？
* 我的資料中心容量必須保留多少才能進行複寫？




=== 計費資料模型

可讓您回答有關儲存資源（磁碟區、內部磁碟區和qtree）上已使用容量和已分配容量的問題。此資料模型可依主機、應用程式和企業實體提供儲存容量計費和責任資訊、同時包含目前和歷史資料。報告資料可依服務層級和儲存層進行分類。

您可以使用此資料模型來找出企業實體所使用的容量、以產生計費報告。此資料模式可讓您建立多種傳輸協定（包括NAS、SAN、FC和iSCSI）的統一報告。

* 對於沒有內部磁碟區的儲存設備、計費報告會顯示各磁碟區的計費。
* 對於具有內部磁碟區的儲存設備：
+
** 如果將業務實體指派給磁碟區、計費報告會依磁碟區顯示計費。
** 如果未將業務實體指派給磁碟區、但指派給qtree、則計費報告會顯示qtree的計費。
** 如果未將業務實體指派給磁碟區且未指派給qtree、則計費報告會顯示內部磁碟區。
** 決定是否依Volume、qtree或內部Volume顯示計費、是針對每個內部Volume進行、因此同一個儲存資源池中的不同內部Volume可以顯示不同層級的計費。




容量資料會在預設時間間隔後清除。如需詳細資訊、請參閱資料倉儲程序。

使用「計費」資料模型的報告可能會顯示不同於使用「儲存容量」資料模型的報告值。

* 對於非NetApp儲存系統的儲存陣列、兩種資料模型的資料相同。
* 對於NetApp和Celerra儲存系統、Chargeback資料模型使用單一層（磁碟區、內部磁碟區或qtree）來計算費用、而儲存容量資料模型則使用多層（磁碟區和內部磁碟區）來計算費用。




=== 庫存資料模型

可讓您回答有關庫存資源的問題、包括主機、儲存系統、交換器、磁碟、磁帶、 qtree、配額、虛擬機器和伺服器、以及一般裝置。庫存資料模型包含數個子目標、可讓您檢視複製、FC路徑、iSCSI路徑、NFS路徑及違規等相關資訊。庫存資料模型不包含歷史資料。您可以用這些資料回答的問題

* 我擁有哪些資產？這些資產在哪裡？
* 誰在使用這些資產？
* 我擁有哪些類型的裝置、以及這些裝置的元件為何？
* 每個作業系統有多少主機、這些主機上有多少連接埠？
* 每個資料中心中、每個廠商都有哪些儲存陣列？
* 每家廠商在每個資料中心有多少部交換器？
* 有多少連接埠未獲授權？
* 我們使用哪些廠商磁帶、以及每個磁帶上有多少連接埠？在我們開始處理報告之前、請先確認所有的一般裝置？
* 主機與儲存磁碟區或磁帶之間有哪些路徑？
* 一般裝置與儲存磁碟區或磁帶之間的路徑為何？
* 每個資料中心有多少次違反每種類型的事件？
* 對於每個複寫的Volume、來源和目標磁碟區是什麼？
* 我的光纖通道主機HBA和交換器之間是否有任何韌體不相容或連接埠速度不相符的情形？




=== 效能資料模型

可讓您回答有關磁碟區、應用程式磁碟區、內部磁碟區、交換器、應用程式、 VM、VMDK、ESX與VM、主機和應用程式節點的比較。使用此資料模型、您可以建立報告來回答幾種效能管理問題：

* 在特定期間內、哪些磁碟區或內部磁碟區尚未使用或存取？
* 我們能否找出應用程式（未使用）儲存設備的任何可能設定錯誤？
* 應用程式的整體存取行為模式為何？
* 階層式磁碟區是否已適當指派給特定應用程式？
* 我們是否可以在不影響應用程式效能的情況下、為目前執行的應用程式使用更便宜的儲存設備？
* 哪些應用程式會對目前設定的儲存設備產生更多存取？


使用交換器效能表時、您可以取得下列資訊：

* 我的主機流量是否透過連線的連接埠達到平衡？
* 哪些交換器或連接埠出現大量錯誤？
* 根據連接埠效能、最常使用的交換器有哪些？
* 根據連接埠效能、未充分利用的交換器有哪些？
* 根據連接埠效能、主機的處理量趨勢為何？
* 過去X天、某個指定主機、儲存系統、磁帶或交換器的效能使用率為何？
* 哪些裝置在特定交換器上產生流量（例如、哪些裝置負責使用高使用率交換器）？
* 我們環境中特定業務單位的處理量是多少？


使用磁碟效能表時、您可以取得下列資訊：

* 根據磁碟效能資料、指定儲存資源池的處理量是多少？
* 使用率最高的儲存資源池為何？
* 特定儲存設備的平均磁碟使用率為何？
* 根據磁碟效能資料、儲存系統或儲存資源池的使用趨勢為何？
* 特定儲存資源池的磁碟使用量趨勢為何？


使用VM和VMDK效能表時、您可以取得下列資訊：

* 我的虛擬環境效能是否最佳？
* 哪些VMDK報告的工作負載最高？
* 如何使用對應至不同資料存放區之VMD回報的效能、來做出重新分層的決策。


效能資料模型包含的資訊可協助您判斷層級的適當性、應用程式的儲存設備組態錯誤、以及磁碟區和內部磁碟區的最後存取時間。此資料模型可提供回應時間、IOPs、處理量、待處理寫入次數及存取狀態等資料。



=== 儲存效率資料模型

可讓您追蹤一段時間內的儲存效率分數和潛力。此資料模型不僅會儲存已配置容量的測量值、也會儲存已使用或已使用的容量（實體測量值）。例如、啟用精簡配置時Cloud Insights 、功能表功能表會顯示從裝置取得的容量。啟用重複資料刪除功能時、您也可以使用此模式來判斷效率。您可以使用儲存效率資料倉儲來回答各種問題：

* 因為實作精簡配置和重複資料刪除技術、我們的儲存效率可節省多少成本？
* 資料中心的儲存節約效益為何？
* 根據過去的容量趨勢、我們何時需要購買額外的儲存設備？
* 如果我們啟用精簡配置和重複資料刪除等技術、容量會增加多少？
* 關於儲存容量、我現在面臨風險嗎？




=== 資料模型事實與維度表

每個資料模型都包含事實表和維度表。

* 事實表：包含測量的資料、例如數量、原始和可用容量。包含外部索引鍵來標註表格的尺寸。
* 維度表：包含有關事實的描述性資訊、例如資料中心和業務單位。維度是一種結構、通常由階層組成、用以分類資料。維度屬性有助於說明維度值。


您可以使用不同或多個維度屬性（在報告中顯示為欄）來建構報告、以存取資料模型中所述每個維度的資料。



=== 資料模型元素中使用的色彩

資料模型元素上的色彩有不同的指示。

* 黃色資產：代表測量結果。
* 非黃色資產：代表屬性。這些值不會集合在一起。




=== 在一份報告中使用多個資料模型

一般而言、每份報告使用一個資料模型。不過、您可以撰寫一份報告、其中結合了多個資料模型的資料。

若要撰寫結合多個資料模型資料的報告、請選擇其中一個資料模型作為基礎、然後寫入SQL查詢、以從其他資料集市存取資料。您可以使用SQL Join功能、將不同查詢的資料合併成單一查詢、以便用來撰寫報告。

例如、假設您想要每個儲存陣列的目前容量、並且想要在陣列上擷取自訂附註。您可以使用儲存容量資料模型來建立報告。您可以使用目前容量和尺寸表中的元素、並新增個別的SQL查詢、以存取庫存資料模型中的註釋資訊。最後、您可以使用儲存名稱和連接條件、將庫存儲存資料連結至Storage Dimension表格、以合併資料。
