---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 裝置解決方案可協助您準確追蹤環境中的效能與庫存。 
---
= 裝置解決規則
:allow-uri-read: 


[role="lead"]
您可以建立裝置解析規則、以識別Cloud Insights 目前無法自動識別的主機、儲存設備和磁帶。您所建立的規則可識別環境中目前的裝置、並可識別新增至環境中的類似裝置。



== 建立裝置解決規則

當您建立規則時、首先要識別規則執行的資訊來源、擷取資訊的方法、以及是否將DNS查詢套用至規則的結果。

[cols="2*"]
|===


| 用於識別裝置的來源 | *主機的SRM別名*包含內嵌主機或磁帶名稱的儲存別名*包含內嵌主機或磁帶名稱的交換器別名*包含內嵌主機名稱的區域名稱 


| 從來源擷取裝置名稱的方法 | *依現值（從SRM擷取名稱）*分隔符號*規則運算式 


| DNS查詢 | 指定您是否使用DNS驗證主機名稱 
|===
您可以在「自動解決規則」索引標籤中建立規則。下列步驟說明規則建立程序。

.程序
. 按一下「*管理>裝置解析度*」
. 在*自動解析規則*索引標籤中、按一下「*+主機規則*」或「*+磁帶規則*」。
+
隨即顯示*解決規則*畫面。

+

NOTE: 按一下「_View matching Criteria _」連結以取得建立規則運算式的說明和範例。

. 在*類型*清單中、選取您要識別的裝置。
+
您可以選取_Host_或_磁帶_。

. 在*來源*清單中、選取您要用來識別主機的來源。
+
根據您選擇的來源Cloud Insights 、畫面上會顯示下列回應：

+
.. *區域*列出Cloud Insights 了需要由下列項目識別的區域和WWN。
.. * SRM *列出Cloud Insights 需要由VMware識別的不明別名
.. *儲存別名*列出Cloud Insights 需要由功能介紹的儲存別名和WWN
.. *交換器別名*會列出Cloud Insights 需要由下列項目識別的交換器別名


. 在「*方法*」清單中、選取您要用來識別主機的方法。
+
|===


| 來源 | 方法 


| SRM | 也就是分隔符號、規則運算式 


| 儲存別名 | 分隔符號、規則運算式 


| 交換器別名 | 分隔符號、規則運算式 


| 區域 | 分隔符號、規則運算式 
|===
+
** 使用分隔符號的規則需要分隔符號和主機名稱的最小長度。主機名稱的最小長度為Cloud Insights 用來識別主機的字元數。僅針對這麼長或更長的主機名稱執行DNS查詢。Cloud Insights
+
對於使用分隔符號的規則、輸入字串會以分隔符號標記、並會建立多個鄰近標記組合的主機名稱候選清單。然後將清單排序、從最大到最小。例如、對於_vipsnq03_hba3_emc3_12ep0_的輸入環、清單會產生下列結果：

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3.
*** Hba3.


** 使用規則運算式的規則需要規則運算式、格式和大小寫敏感度選擇。


. 按一下「*執行AR*」以執行所有規則、或按一下按鈕中的向下箭號以執行您建立的規則（以及自上次完整執行AR之後所建立的任何其他規則）。
+
規則執行的結果會顯示在「* FC identify *（* FC識別*）」索引標籤中。





== 開始自動更新裝置解析度

裝置解析度更新會認可自上次執行全自動裝置解析以來所新增的手動變更。執行更新只能用來提交及執行新的手動項目、以供裝置解析度組態使用。不會執行完整的裝置解析度執行。

.程序
. 登入Cloud Insights 到這個Web UI。
. 按一下「*管理>裝置解析度*」
. 在*設備分辨率*屏幕中，單擊*運行AR*按鈕中的向下箭頭。
. 按一下「*更新*」開始更新。




== 規則輔助手動識別

此功能適用於您想要執行特定規則或規則清單的特殊情況（無論是否需要一次性重新排序）、以解析未知主機、儲存設備和磁帶設備。

您有許多尚未識別的裝置、也有多個規則可成功識別其他裝置。


NOTE: 如果來源僅包含主機或裝置名稱的一部分、請使用規則運算式規則並加以格式化、以新增遺失的文字。

.程序
. 登入Cloud Insights 到這個Web UI。
. 按一下「*管理>裝置解析度*」
. 單擊* Fibre Channel identi*（光纖通道識別*）選項卡。
+
系統會顯示裝置及其解析度狀態。

. 選取多個未識別的裝置。
. 按一下*大量動作*並選取*設定主機解析度*或*設定磁帶解析度*。
+
系統會顯示識別畫面、其中包含已成功識別裝置的所有規則清單。

. 將規則順序變更為符合您需求的訂單。
+
規則順序會在識別畫面中變更、但不會全域變更。

. 選取符合您需求的方法。


從最上層開始、執行主機解析程序的順序。Cloud Insights

遇到適用的規則時、規則名稱會顯示在規則欄中、並標示為手動。

相關：link:task_device_resolution_fibre_channel.html["Fibre Channel裝置解析度"]
link:task_device_resolution_ip.html["IP裝置解析度"]
link:task_device_resolution_preferences.html["設定裝置解析度偏好設定"]
