---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: 設定Dell EMC Celerra資料收集器。 
---
= Dell EMC VNX檔案（前身為Celerra統一化儲存系統）資料收集器
:allow-uri-read: 


[role="lead"]
此資料收集器會從VNX檔案儲存系統取得庫存資訊。對於組態、此資料收集器需要儲存處理器的IP位址、以及唯讀使用者名稱和密碼。



== 術語

從VNX檔案資料收集器取得下列庫存資訊。Cloud Insights對於由SfeS庫 取得的每種資產類型Cloud Insights 、都會顯示此資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | 詞彙Cloud Insights 


| Celerra網路伺服器/ Celerra儲存資源池 | 儲存資源池 


| 檔案系統 | 內部Volume 


| 資料移轉 | 控制器 


| 掛載於資料移動工具上的檔案系統 | 檔案共用 


| CIFS與NFS匯出 | 分享 


| 磁碟區 | 後端LUN 
|===
附註：這些只是通用的術語對應、可能不代表此資料收集器的每個案例。



== 需求

您需要下列項目來設定此資料收集器：

* 儲存處理器的IP位址
* 唯讀使用者名稱和密碼
* SSH連接埠22




== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| VNX檔案IP位址 | VNX檔案裝置的IP位址或完整網域名稱 


| 使用者名稱 | 用於登入VNX檔案裝置的名稱 


| 密碼 | 用於登入VNX檔案裝置的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 庫存輪詢時間間隔（分鐘） | 庫存輪詢之間的時間間隔。預設值為20分鐘。 
|===


== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：



==== 庫存

[cols="2*"]
|===
| 問題： | 試用： 


| 錯誤：DART更新進行中無法繼續 | 可能的解決方案：暫停資料收集器、等待DART升級完成、再嘗試另一個擷取要求。 
|===
如需其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["資料收集器支援對照表"]。
