---
sidebar: sidebar 
permalink: task_config_cs_data_collectors.html 
keywords: acquisition, AU, data collector, collector 
summary: 設定資料收集器 
---
= 設定資料收集器
:allow-uri-read: 


[role="lead"]
您可在Cloud Insights 您的支援環境中設定資料收集器、以便從資料中心的主機、服務或裝置收集資料。

.開始之前
* 您必須擁有帳戶擁有者或管理權限、才能設定資料收集器。
* 您必須先設定擷取單元（適用於Infrastrstructure）或代理程式（適用於服務或主機）、才能開始收集資料。
* 您需要用來收集資料的基礎架構裝置的認證資料。
+
您想要從中收集資料的所有裝置都需要裝置網路位址、帳戶資訊和密碼。





=== 認證安全性

資料收集器認證資料會在輸入Cloud Insights 到SURITY時加密、並先由AU的公開金鑰加密傳送至擷取單位（AU）、然後再透過HTTPS加密。當AU使用加密值與裝置和軟體通訊時、會將其解密。



=== 設定資料收集器

* 在「支援」功能表中、按一下「*管理」>「資料收集器*」Cloud Insights 、然後按一下「*+資料收集器*」按鈕。您可以選擇顯示所有的資料收集器、或是篩選、根據您的訂閱、僅顯示可用的資料收集器。


* 視您選擇的資料收集器類型而定、安裝步驟可能有所不同。




==== 作業系統：

您必須安裝至少一個Cloud Insights 支援程序才能開始從環境中收集作業系統或服務資料。您可以安裝任意數量的代理程式。每個代理程式都能從多個服務收集資料。

除了從服務收集資料之外、每個代理程式也會做為安裝該代理程式的VM /主機的資料收集器。收集的資料會以儀表板小工具或查詢中的「節點」資料呈現。

. 按一下您存取Cloud Insights 的VM或主機（即Node）平台類型或作業系統。
. 選擇代理程式存取金鑰。
. 將顯示的命令複製到剪貼簿。您可以按一下剪貼簿圖示、快速複製命令。
. 在代理VM/主機上開啟終端機/命令視窗、然後貼上命令。按Enter鍵執行命令。
. 安裝代理程式之後、按一下*「Finish」（完成）*。代理程式開始收集資料。
+
在儀表板中顯示節點資料或可供查詢之前、最多可能需要兩個輪詢期間。





==== 服務：

服務資料收集器是以Telewraf代理程式為基礎的收集器、例如Docker或Kibana。

.開始之前
* 您必須至少有一個Cloud Insights 支援程序才能從您的環境中收集服務資料。如果您尚未安裝代理程式、則在設定服務資料收集器時、系統會提示您安裝代理程式。
* 您要從中收集資料的服務必須在您的環境中安裝並執行。
+
.. 按一下服務資料收集器。
.. 選擇代理程式作業系統或平台。如果您尚未安裝平台的代理程式、請依照指示進行。
.. 選擇代理程式存取金鑰。
.. 按一下 * 繼續 * 。
.. 請依照指示設定資料收集器。您可以按一下剪貼簿圖示、快速複製顯示的命令或程式碼片段。
.. 正確設定資料收集器之後、按一下*完成*。
+
在儀表板中顯示服務資料或可供查詢之前、可能需要兩個輪詢期間。







==== 基礎架構：

基礎架構資料收集器包括儲存設備或交換器等項目。

.開始之前
* 您必須設定至少一個擷取單位、才能開始收集基礎架構資料。
+
.. 按一下基礎架構資料收集器。
.. 輸入資料收集器的名稱。名稱可以包含下列字元：


* 字母（a到z）
* 編號（0-9）
* 連字號（-）
* 底線（_）
* 期間（.）
* 空間（）
+
名稱不得以空格、句點或連字號開頭或結尾。

+
.. 輸入要與此資料收集器建立關聯的擷取單位。
.. 在「組態」畫面中輸入必填欄位。
.. 按一下*進階組態*以輸入其他組態欄位。並非所有的資料收集器都需要進階組態。
.. 按一下「*測試組態*」以確認資料收集器已正確設定。
.. 完成後、按一下*新增Collector *。




如需新增擷取單位的說明、請參閱 link:task_configure_acquisition_unit.html["設定擷取單位"]

+在儀表板顯示環境資料或可供查詢之前、可能需要兩個輪詢期間。
