---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 使用註釋追蹤資料。 
---
= 定義註釋
:allow-uri-read: 


[role="lead"]
自訂Cloud Insights 功能時、若要根據公司需求追蹤資料、您可以定義專業的附註、稱為附註、並將其指派給您的資產。

您可以使用資產生命週期結束、資料中心、建置位置、儲存層或Volume服務層級等資訊、為資產指派附註。

使用註釋來協助監控環境、包括下列高層級工作：

* 建立或編輯所有註釋類型的定義。
* 顯示資產頁面、並將每項資產與一或多個附註建立關聯。
+
例如、如果某項資產正在租賃、而租賃在兩個月內到期、您可能會想要在該資產上套用生命週期結束附註。這有助於防止其他人長期使用該資產。

* 建立規則以自動將註釋套用至同一類型的多個資產。
* 依資產附註篩選資產。




== 預設註釋類型

提供一些預設的註釋類型。Cloud Insights這些附註可用來篩選或分組資料。

您可以將資產與預設註釋類型建立關聯、例如：

* 資產生命週期、例如生日、日出或生命週期結束
* 裝置的位置資訊、例如資料中心、建築物或樓層
* 資產分類、例如依品質（階層）、依連線裝置（交換器層級）或依服務層級分類
* 狀態、例如Hot（高使用率）


下表列出Cloud Insights提供的註釋類型。

[cols="30,53, 16"]
|===


| 註釋類型 | 說明 | 類型 


| 別名 | 資源的使用者易記名稱 | 文字 


| 運算資源群組 | 主機和VM檔案系統資料收集器所使用的群組指派 | 清單 


| 資料中心 | 實體位置 | 清單 


| 熱 | 設備經常使用或在容量臨界值時使用 | 布林值 


| 附註 | 與資源相關的註解 | 測試 


| 服務層級 | 一組可指派給資源的支援服務層級。提供內部磁碟區、qtree和磁碟區的排序選項清單。編輯服務層級以設定不同層級的效能原則。 | 清單 


| 日落後 | 設定的臨界值、在此之後無法對該裝置進行新的配置。適用於計畫性移轉和其他擱置中的網路變更。 | 日期 


| 交換器層級 | 預先定義的選項、用於設定交換器類別。通常、這些名稱會保留在裝置的使用壽命內、不過您可以編輯這些名稱。僅適用於交換器。 | 清單 


| 層級 | 可用於定義環境中的不同服務層級。階層可以定義層級類型、例如所需的速度（例如金級或銀級）。此功能僅適用於內部磁碟區、qtree、儲存陣列、儲存資源池和磁碟區。 | 清單 


| 違規嚴重性 | 在最高至最低重要性的階層中、排列違規（例如遺失主機連接埠或缺少備援）的等級（例如MAJOR）。 | 清單 
|===

NOTE: 別名、資料中心、Hot、服務層級、 交換器層級、層級和違規嚴重性是系統層級的附註、您無法刪除或重新命名；您只能變更其指派的值。



== 建立自訂註釋

使用註釋、您可以新增符合業務需求的自訂業務專屬資料至資產。雖然提供一組預設附註、但您可能會發現您想要以其他方式檢視資料。Cloud Insights自訂附註中的資料可補充已收集的裝置資料、例如儲存設備製造商、磁碟區數和效能統計資料。您使用註釋新增的資料Cloud Insights 不會被任何資訊所發現。

.步驟
. 在功能表中、按一下*管理>註釋*。Cloud Insights
+
「附註」頁面會顯示附註清單。

. 按一下「*+附加*」
. 輸入註釋的*名稱*和*說明*。
+
您可以在這些欄位中輸入最多255個字元。

. 按一下「*類型*」、然後選取下列其中一個選項、代表此註釋所允許的資料類型：


.註釋類型
布林值:: 建立下拉式清單、並選擇「yes（是）」和「no（否）」例如、「直接附加」註釋為布林型。
日期:: 這會建立一個保留日期的欄位。例如、如果註釋是日期、請選取此選項。
清單:: 建立下列其中一項：
+
--
* 下拉式固定清單
+
當其他人在裝置上指派此註釋類型時、他們無法新增更多值至清單。

* 下拉式彈性清單
+
如果您在建立此清單時選取「即時新增值」選項、則當其他人在裝置上指派此註釋類型時、他們可以將更多值新增至清單。



--
數量:: 建立一個欄位、讓指派附註的使用者可以輸入一個數字。例如、如果註釋類型為「Floor」、則使用者可以選取「Number」的值類型、然後輸入樓層編號。
文字:: 建立允許自由格式文字的欄位。例如、您可以輸入「Language（語言）」作為註釋類型、選取「Text（文字）」作為值類型、然後輸入語言作為值。



NOTE: 設定類型並儲存變更後、便無法變更註釋類型。如果您需要變更類型、則必須刪除註釋並建立新的註釋。

. 如果您選取「清單」作為註釋類型、請執行下列動作：
+
.. 如果您想要在資產頁面上新增更多值至註釋、請選取*「即時新增值」*、以建立彈性清單。
+
例如、假設您在資產頁面上、資產的「城市」註釋會顯示值為「底特律」、「坦帕」和「波士頓」。如果您選取*「即時新增值」選項、您可以直接在資產頁面上新增城市（例如舊金山和芝加哥）的其他值、而不必前往「附註」頁面新增這些值。如果您未選擇此選項、則在套用註釋時、將無法新增註釋值；這會建立固定清單。

.. 在*值*和*說明*欄位中輸入值和說明。
.. 按一下「*+附加*」以新增其他值。
.. 按一下「垃圾桶」圖示以刪除值。


. 按一下「*儲存*」
+
您的註釋會出現在「註釋」頁面的清單中。



在UI中、註釋可立即使用。
