---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: 設定IBM PowerVM資料收集器。 
---
= 設定IBM PowerVM資料收集器
:allow-uri-read: 


[role="lead"]
IBM PowerVM（SSH）資料收集器用於收集有關在由硬體管理主控台（HMC）管理的IBM電源硬體執行個體上執行的虛擬分割區資訊。



== 術語

從IBM Power硬體執行個體上執行的虛擬分割區取得庫存資訊。Cloud Insights對於所取得的每種資產類型、都會顯示該資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | 詞彙Cloud Insights 


| hdisk | 虛擬磁碟 


| 託管系統 | 主機 


| LPAR、VIO伺服器 | 虛擬機器 


| Volume群組 | 資料儲存區 


| 實體Volume | LUN 
|===
附註：這些只是通用的術語對應、可能不代表此資料收集器的每個案例。



== 需求

若要設定及使用此資料收集器、必須符合下列需求：

* 硬體管理主控台（HMC）的IP位址
* 使用者名稱和密碼、可透過SSH存取硬體管理主控台（HMC）
* 連接埠需求SSH-22
* 檢視所有管理系統和邏輯分割安全性網域的權限
+
使用者也必須擁有HMC組態的「檢視」權限、以及收集HMC主控台安全性群組的VPD資訊的能力。使用者也必須能夠在「邏輯分割區」安全性群組下存取「虛擬IO伺服器命令」。最佳做法是從操作員角色開始、然後移除所有角色。HMC上的唯讀使用者沒有在AIX主機上執行代理命令的權限。

* IBM最佳實務做法是由兩個以上的HMC監控裝置。請注意、這可能會導致OnCommand Insight 無法回報重複的裝置、因此強烈建議您將備援裝置新增至此資料收集器的「進階組態」中的「排除裝置」清單。




== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| 硬體管理主控台（HMC）IP位址 | PowerVM硬體管理主控台的IP位址或完整網域名稱 


| HMC使用者 | 硬體管理主控台的使用者名稱 


| 密碼 | 硬體管理主控台使用的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 庫存輪詢時間間隔（分鐘） | 庫存輪詢之間的時間間隔。預設值為20分鐘。 


| SSH連接埠 | 用於SSH至PowerVM的連接埠 


| 密碼 | 硬體管理主控台使用的密碼 


| 重試次數 | 嘗試進行庫存重試的次數 


| 排除裝置 | 以逗號分隔的裝置ID清單或要排除的顯示名稱 
|===


== 疑難排解

如需此資料收集器的其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["資料收集器支援對照表"]。
