---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 摘要： 
---
= 管理已設定的資料收集器
:allow-uri-read: 


[role="lead"]
「安裝的資料收集器」頁面可讓您存取已設定Cloud Insights 為供使用的資料收集器。您可以使用此頁面來修改現有的資料收集器。

.步驟
. 在「支援」功能表中、按一下Cloud Insights 「*管理」>「資料收集器*」
+
此時會顯示「可用的資料收集器」畫面。

. 按一下*安裝的資料收集器*
+
隨即顯示所有已安裝的資料收集器清單。此清單提供收集器名稱、狀態、收集器正在存取的IP位址、以及上次從裝置取得資料的時間。可在此畫面上執行的動作包括：

+
** 控制輪詢
** 變更資料收集器認證資料
** 複製資料收集器






== 控制資料收集器輪詢

變更資料收集器之後、您可能希望它立即輪詢以檢查變更、或者您可能想要在處理問題時、將資料收集器上的資料收集延遲一、三或五天。

.步驟
. 在「支援」功能表中、按一下Cloud Insights 「*管理」>「資料收集器*」
. 按一下*安裝的資料收集器*
. 選取您要變更之資料收集器左側的核取方塊
. 按一下*大量動作*、然後選取您要執行的輪詢動作。
+
您可以在多個資料收集器上同時執行大量動作。選取資料收集器、然後從*大量行動*功能表中選擇要執行的動作。





== 編輯資料收集器資訊

您可以編輯現有的資料收集器設定資訊。

.若要編輯單一資料收集器：
. 在「支援」功能表中、按一下「*管理」>「資料收集器*」Cloud Insights 以開啟已安裝的資料收集器清單。
. 在您要修改之資料收集器右側的選項功能表中、按一下*編輯*。
+
隨即開啟「編輯收集器」對話方塊。

. 輸入變更內容、然後按一下*測試組態*以測試新組態、或按一下*儲存*以儲存組態。


您也可以編輯多個資料收集器：

. 選取您要變更之每個資料收集器左側的核取方塊。
. 按一下「*大量動作*」按鈕、然後選擇「*編輯*」以開啟「編輯資料收集器」對話方塊。
. 如前所述修改欄位。
+

NOTE: 所選的資料收集器必須是相同的廠商和機型、並位於相同的擷取設備上。

+
編輯多個資料收集器時、資料收集器名稱欄位會顯示「混合」、無法編輯。其他欄位（例如使用者名稱和密碼）會顯示「混合」、並可加以編輯。在選取的資料收集器中共用相同值的欄位會顯示目前值、並可加以編輯。

+
編輯多個資料收集器時、*測試組態*按鈕無法使用。





== 複製資料收集器

使用複製工具、您可以快速新增與其他資料來源具有相同認證和屬性的資料來源。複製可讓您輕鬆設定相同裝置類型的多個執行個體。

.步驟
. 在「支援」功能表中、按一下Cloud Insights 「*管理」>「資料收集器*」。
. 按一下*安裝的資料收集器*。
. 按一下您要複製之資料收集器左側的核取方塊。
. 在所選資料收集器右側的選項功能表中、按一下* Clone（複製）*。
+
此時會顯示Clone Data Collector（Clone Data Collector）對話框。

. 在必填欄位中輸入新資訊。
. 按一下「 * 儲存 * 」。


.完成後
複製作業會複製所有其他屬性和設定、以建立新的資料收集器。



== 在資料收集器上執行大量動作

您可以同時編輯多個資料收集器的部分資訊。此功能可讓您在多個資料收集器上啟動輪詢、延遲輪詢及恢復輪詢。此外、您也可以刪除多個資料收集器。

.步驟
. 在「支援」功能表中、按一下Cloud Insights 「*管理」>「資料收集器*」
. 按一下*安裝的資料收集器*
. 按一下您要修改之資料收集器左側的核取方塊。
. 在右側的選項功能表中、按一下您要執行的選項。


.完成後
您選取的作業會在資料收集器上執行。當您選擇刪除資料收集器時、會顯示一個對話方塊、要求您遵守此動作。
