---
sidebar: sidebar 
permalink: task-aws-key-management.html 
keywords: aws, amazon, encryption, NVE, NetApp volume encryption, KMIP, kms, key manager service 
summary: 為您的第三方金鑰管理服務使用 AWS 的金鑰管理服務。 
---
= 使用 AWS 金鑰管理服務管理金鑰
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["AWS 的金鑰管理服務（ KMS ）"^] 在ONTAP Google Cloud Platform部署的應用程式中保護您的不加密金鑰。

您可以使用 CLI 或 ONTAP REST API 來啟用 AWS KMS 的金鑰管理。

使用 KMS 時、請注意、根據預設、資料 SVM 的 LIF 會用於與雲端金鑰管理端點通訊。節點管理網路用於與 AWS 的驗證服務進行通訊。如果叢集網路設定不正確、叢集將無法正確使用金鑰管理服務。

.開始之前
* Cloud Volumes ONTAP 必須執行 9.12.0 版或更新版本
* 您必須已安裝 Volume Encryption （ VE ）授權和
* 您必須已安裝多租戶加密金鑰管理（ MTEKM ）授權。
* 您必須是叢集或SVM管理員
* 您必須擁有有效的 AWS 訂閱



NOTE: 您只能設定資料 SVM 的金鑰。



== 組態

.AWS
. 您必須建立 link:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant["授予"^] 適用於管理加密的 IAM 角色所使用的 AWS KMS 金鑰。IAM 角色必須包含允許下列作業的原則：
+
** `DescribeKey`
** `Encrypt`
** `Decrypt`
若要建立授予、請參閱 link:https://docs.aws.amazon.com/kms/latest/developerguide/create-grant-overview.html["AWS 文件"^]。


. link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["將原則新增至適當的 IAM 角色。"^] 原則應支援 `DescribeKey`、 `Encrypt`和 `Decrypt` 營運：


.Cloud Volumes ONTAP
. 切換至您的 Cloud Volumes ONTAP 環境。
. 切換至進階權限層級：
`set -privilege advanced`
. 啟用 AWS 金鑰管理程式：
`security key-manager external aws enable -vserver _data_svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. 出現提示時、請輸入秘密金鑰。
. 確認 AWS KMS 已正確設定：
`security key-manager external aws show -vserver _svm_name_`

