---
sidebar: sidebar 
permalink: task_isolate_root_volume.html 
summary: 查詢高I/O密度時、您想要排除根磁碟區。 
keywords: NetApp, root volume, high I/O, 
---
= 確保IO密度報告僅說明內部資料磁碟區
:allow-uri-read: 


[role="lead"]
NetApp根Volume包含用於管理儲存系統的目錄和組態檔案。查詢高I/O密度時、您想要排除這些根磁碟區。

監控環境時、更重要的是判斷哪些內部資料磁碟區產生高I/O密度的數字。為了準確識別資料磁碟區、您必須將NetApp內部磁碟區與用來監控I/O密度的查詢區隔離開來。

本指南說明如何輕鬆識別NetApp根集合體、將其與內部Volume查詢結果區隔、以及建立規則、以在新增至系統時排除任何新的NetApp根集合體。下列Insight功能可確保您的I/O密度報告是從內部資料磁碟區衍生而來：

* 系統會建立查詢、以識別Insight監控的所有NetApp根集合體。
* 每個NetApp根集合體都會指派附註。
* 建立註釋規則、將註釋套用至新的NetApp根Aggregate。


本指南中的步驟也適用於其他廠商的儲存系統。您需要識別包含目錄和組態檔的磁碟區、以便管理儲存系統、並使用類似步驟排除這些磁碟區。



== 建立查詢以識別您環境中的NetApp根集合體

查詢可根據使用者選取的條件、提供精細的搜尋層級。使用查詢可讓您搜尋環境中包含NetApp根Aggregate的內部磁碟區。

. 步驟
. 建立查詢以識別您環境中的NetApp根集合體：按一下*查詢>新查詢>選取資源類型*（？）
. 按一下*儲存資源池*
. 輸入根Aggregate的名稱
+
此範例使用"aggr0"做為名稱。建立Aggregate時、只能遵循下列名稱需求：。必須以字母或底線開頭（_）。...它只能包含字母、數字和底線。...可以少於250個字元。在大多數情況下、Agggr0、aggr_0或類似名稱。可能需要迭代程序來識別環境中的所有NetApp根集合體。

. 按一下「*儲存*」、然後輸入新查詢的名稱。
+
如前所述、這可能是一個迭代程序、需要多個查詢來識別所有NetApp根集合體。





== 為查詢傳回的根磁碟區建立附註

附註是您指派給資產的專屬附註、可讓您根據資產附註來篩選資產。您所建立的註釋將用於識別您環境中的NetApp根集合體、並確保它們不會包含在特定報告中。

.開始之前
您必須已識別出要從「高I/O密度」報告中排除的所有根Aggregate。

.步驟
. 在功能表中、按一下*管理>註釋* Cloud Insights
. 按一下「*新增*」
+
.. 輸入註釋名稱：* RootAggr*
.. 輸入註釋說明：*從「高I/O密度」報告中移除根Aggregate *
.. 輸入註釋類型：*布林*


. 按一下「*儲存*」




== 建立註釋規則、將特定Aggregate排除在I/O密度報告之外、予以自動化

您可以使用註釋規則、自動將註釋套用至多個資產、作為手動套用註釋至個別資產的替代方法。附註規則是根據您建立的查詢而定、當在系統上執行時、會將新資產新增至現有的資產集。當這些資產集合從報告中排除時、新資產也會自動排除在外。

.開始之前
您必須建立並儲存查詢、以識別您在環境中識別的NetApp根集合體。。步驟。在「功能表」工具列中、按一下Cloud Insights 「*管理>註釋規則*」。按一下「*新增*」

+「新增規則」對話方塊會顯示：...在名稱方塊中、輸入描述規則的唯一名稱：*「RootAggrExclude*」。按一下查詢、然後選取Insight應使用的查詢、將註釋規則套用至：*「Aggregate0*」。按一下註釋、然後選取：*「root agg exclude」*。按一下*值*並輸入*真*
