---
sidebar: sidebar 
permalink: task_config_cs_amazon_fsx.html 
keywords: Cloud, Storage, AWS, Fsx 
summary: 使用資料收集器從裝置收集檔案和使用者存取資料。Cloud Secure 
---
= Amazon FSX for NetApp ONTAP 的「架構組態」
:allow-uri-read: 


[role="lead"]
此資料收集器可收集Amazon FSX for NetApp ONTAP 的檔案與使用者存取資料。此資料收集器將逐步提供給Cloud Insights 整個「穩定」服務區域。如果Cloud Insights 您在自己的《不景》中沒有看到此收藏器的圖示、請聯絡您的銷售人員。



=== 代理機器組態

請使用下列步驟來設定機器以做Cloud Secure 為一個物件代理程式：

. 登入AWS主控台並瀏覽至EC2-instances頁面、然後選取Launch instance。
. 選取RHEL或CentOS AMI的適當版本、如中所述 link:concept_cs_agent_requirements.html["需求"]。
. 在Amazon FSX for NetApp ONTAP 的VPC和子網路中建立「代理程式」方塊、此方塊與Amazon FSX for NetApp的執行個體位於相同的VPC和子網路中。
+
或是Agent Box應位於VPC中、可連線至Amazon FSX for NetApp ONTAP VPC。

+
請確定代理程式與Amazon FSX for NetApp ONTAP 之間存在雙向通訊。

. 選取T2.xLarge（4個vCPU和16 GB RAM）作為已配置資源。
+
.. 建立EC2執行個體。


. 使用YUM套件管理程式安裝所需的Linux套件：
+
.. 安裝wGet並解壓縮原生Linux套件。






=== 安裝Cloud Secure 此功能

. 以系統管理員或帳戶擁有者身分登入Cloud Insights 您的支援環境。
. 瀏覽Cloud Secure 至「資料收集器」>「資料收集器」、然後按一下「值機員」索引標籤。
. 按一下「+Agent」、並將RHEL指定為目標平台。
. 複製代理程式安裝命令。
. 將「代理程式安裝」命令貼到您登入的RHEL EC2執行個體中。
+
只Cloud Secure 要符合所有的代理程式先決條件、即可安裝此程式。



如需詳細步驟、請參閱Cloud Secure 《》 link:task_cs_add_agent.html["代理程式安裝"] 第頁、
