---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: 設定IBM SAN Volume Controller資料收集器。 
---
= 設定IBM SAN Volume Controller資料收集器
:allow-uri-read: 


[role="lead"]
IBM SAN Volume Controller（SVC）資料收集器會使用SSH收集庫存與效能資料、支援執行SVC作業系統的各種裝置。

支援的裝置清單包括SVC、v7000、v5000和v3700等機型。如Cloud Insights 需支援的機型和韌體版本、請參閱支援表。



== 術語

從IBM SVC資料收集器取得下列庫存資訊。Cloud Insights對於由SfeS庫 取得的每種資產類型Cloud Insights 、都會顯示此資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | 詞彙Cloud Insights 


| 磁碟機 | 磁碟 


| 叢集 | 儲存設備 


| 節點 | 儲存節點 


| Mdisk群組 | 儲存資源池 


| vDisk | Volume 


| 磁碟 | 後端LUN和路徑 
|===
附註：這些只是通用的術語對應、可能不代表此資料收集器的每個案例。



=== 庫存需求

* 每個SVC叢集的IP位址
* 連接埠22可用
* 唯讀使用者名稱和密碼




=== 效能要求

* SVC主控台、適用於任何SVC叢集、且適用於SVC探索基礎套件。
* 認證僅在將效能檔案從叢集節點複製到組態節點時、才需要管理存取層級。
* 透過SSH連線至SVC叢集並執行：_svctask startstats -interval 1_來啟用資料收集
+
附註：或者、您也可以使用SVC管理使用者介面來啟用資料收集功能。





== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| 叢集IP位址 | SVC儲存設備的IP位址或完整網域名稱 


| 庫存使用者名稱 | SVC CLI的使用者名稱 


| 庫存密碼 | SVC CLI的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 庫存輪詢時間間隔（分鐘） | 庫存輪詢之間的時間間隔。預設值為40分鐘。 


| 效能意見調查時間間隔（秒） | 效能輪詢之間的時間間隔。預設值為300秒。 


| 清除傾印的統計資料檔案 | 選取此核取方塊以清除傾印的統計資料檔案 
|===


== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：

[cols="2*"]
|===
| 問題： | 試用： 


| 錯誤：「無法起始命令、因為命令並未在組態節點上執行。」 | 必須在組態節點上執行命令。 
|===
如果您在使用此資料收集器時遇到問題、請嘗試下列事項：

[cols="2*"]
|===
| 問題： | 試用： 


| 錯誤：「無法起始命令、因為命令並未在組態節點上執行。」 | 必須在組態節點上執行命令。 
|===
如需此資料收集器的其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["資料收集器支援對照表"]。
