---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: 部署 Cloud Volumes ONTAP 時、您可以選擇符合工作負載需求的預先設定系統、或是建立自己的組態。如果您選擇自己的組態、應該瞭解可用的選項。 
---
= 在Cloud Volumes ONTAP Google Cloud規劃您的不一樣組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 Cloud Volumes ONTAP Google Cloud 中部署時、您可以選擇符合工作負載需求的預先設定系統、或是建立自己的組態。如果您選擇自己的組態、應該瞭解可用的選項。



== 選擇Cloud Volumes ONTAP 一個不含功能的授權

有多種授權選項可供Cloud Volumes ONTAP 選擇。每個選項都能讓您選擇符合需求的消費模式。

* link:concept-licensing.html["深入瞭Cloud Volumes ONTAP 解適用於此功能的授權選項"]
* link:task-set-up-licensing-google.html["瞭解如何設定授權"]




== 選擇支援的地區

支援大部分Google Cloud地區的支援。Cloud Volumes ONTAP https://cloud.netapp.com/cloud-volumes-global-regions["檢視支援區域的完整清單"^]。



== 選擇支援的機器類型

根據您選擇的授權類型、支援多種機器類型。 Cloud Volumes ONTAP

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["支援的GCP組態Cloud Volumes ONTAP"^]



== 瞭解儲存限制

一個不含資源的系統的原始容量上限 Cloud Volumes ONTAP 與授權有關。其他限制會影響集合體和磁碟區的大小。在規劃組態時、您應該注意這些限制。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["適用於GCP的儲存限制Cloud Volumes ONTAP"^]



== 在 GCP 中調整系統大小

調整 Cloud Volumes ONTAP 您的支援規模、有助於滿足效能與容量的需求。在選擇機器類型、磁碟類型和磁碟大小時、您應該注意幾個關鍵點：

機器類型:: 請查看中支援的機器類型 http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["發行說明 Cloud Volumes ONTAP"^] 然後檢視 Google 提供的每種受支援機器類型的詳細資料。將工作負載需求與機器類型的 vCPU 和記憶體數量配對。請注意、每個 CPU 核心都能提升網路效能。
+
--
如需詳細資料、請參閱下列內容：

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud 文件： N1 標準機器類型"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud 文件：效能"^]


--
GCP 磁碟類型:: 當您建立 Cloud Volumes ONTAP 用於資料的 Volume 時、您需要選擇 Cloud Volumes ONTAP 基礎雲端儲存設備、以便將其用於磁碟。磁碟類型可以是下列任一種：
+
--
* _Zonal SSD持續式磁碟_：SSD持續式磁碟最適合需要高隨機IOPS速率的工作負載。
* _分區平衡的持續磁碟_：這些SSD可提供較低的每GB IOPS、以平衡效能與成本。
* _Zonal Standard持續式磁碟_：標準持續式磁碟經濟實惠、可處理連續讀寫作業。
+
如需詳細資料、請參閱 https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 文件：分區持續磁碟（標準和 SSD ）"^]。



--
GCP 磁碟大小:: 部署 Cloud Volumes ONTAP 一套系統時、您需要選擇初始磁碟大小。之後、您可以讓BlueXP為您管理系統容量、但如果您想自行建置集合體、請注意下列事項：
+
--
* 集合體中的所有磁碟大小必須相同。
* 判斷您需要的空間、同時考量效能。
* 持續性磁碟的效能會隨著磁碟大小和系統可用的 vCPU 數目而自動擴充。
+
如需詳細資料、請參閱下列內容：

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 文件：分區持續磁碟（標準和 SSD ）"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud 文件：最佳化持續磁碟和本機 SSD 效能"^]




--




== 檢視預設系統磁碟

除了儲存使用者資料之外、BlueXP也購買雲端儲存設備來儲存Cloud Volumes ONTAP 作業系統資料（開機資料、根資料、核心資料和NVRAM）。為了規劃目的、在部署Cloud Volumes ONTAP 完更新之前、您可能需要先檢閱這些詳細資料。

* link:reference-default-configs.html#google-cloud-single-node["在Cloud Volumes ONTAP Google Cloud中檢視系統資料的預設磁碟"]。
* https://cloud.google.com/compute/quotas["Google Cloud文件：資源配額"^]
+
Google Cloud Compute Engine會強制執行資源使用量配額、因此您應該在部署Cloud Volumes ONTAP 時確保未達到上限。




TIP: 連接器也需要系統磁碟。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["檢視Connector預設組態的詳細資料"^]。



== 收集網路資訊

在 Cloud Volumes ONTAP GCP 中部署時、您需要指定虛擬網路的詳細資料。您可以使用工作表向系統管理員收集資訊。

* 單節點系統的網路資訊 *

[cols="30,70"]
|===
| GCP 資訊 | 您的價值 


| 區域 |  


| 區域 |  


| VPC 網路 |  


| 子網路 |  


| 防火牆原則（如果使用您自己的） |  
|===
* 多個區域中 HA 配對的網路資訊 *

[cols="30,70"]
|===
| GCP 資訊 | 您的價值 


| 區域 |  


| 節點 1 的區域 |  


| 節點 2 的區域 |  


| 中介人區域 |  


| VPC-0 和子網路 |  


| VPC-1 和子網路 |  


| VPC-2 和子網路 |  


| VPC-3 和子網路 |  


| 防火牆原則（如果使用您自己的） |  
|===
* 單一區域中 HA 配對的網路資訊 *

[cols="30,70"]
|===
| GCP 資訊 | 您的價值 


| 區域 |  


| 區域 |  


| VPC-0 和子網路 |  


| VPC-1 和子網路 |  


| VPC-2 和子網路 |  


| VPC-3 和子網路 |  


| 防火牆原則（如果使用您自己的） |  
|===


== 選擇寫入速度

BlueXP可讓您選擇Cloud Volumes ONTAP 適合的寫入速度設定、但Google Cloud中的高可用度（HA）配對除外。在您選擇寫入速度之前、您應該先瞭解一般與高設定之間的差異、以及使用高速寫入速度時的風險與建議。 link:concept-write-speed.html["深入瞭解寫入速度"]。



== 選擇Volume使用設定檔

包含多項儲存效率功能、可減少您所需的總儲存容量。 ONTAP在BlueXP中建立磁碟區時、您可以選擇啟用這些功能的設定檔或停用這些功能的設定檔。您應該深入瞭解這些功能、以協助您決定要使用的設定檔。

NetApp 儲存效率功能提供下列效益：

資源隨需配置:: 為主機或使用者提供比實體儲存資源池實際擁有更多的邏輯儲存設備。儲存空間不會預先配置儲存空間、而是會在寫入資料時動態分配給每個磁碟區。
重複資料刪除:: 找出相同的資料區塊、並以單一共用區塊的參考資料取代這些區塊、藉此提升效率。這項技術可消除位於同一個磁碟區的備援資料區塊、進而降低儲存容量需求。
壓縮:: 藉由壓縮主儲存設備、次儲存設備和歸檔儲存設備上磁碟區內的資料、來減少儲存資料所需的實體容量。

