---
sidebar: sidebar 
permalink: task-google-key-manager.html 
keywords: google cloud, encryption, NVE, NetApp volume encryption, KMIP, GCP, GCP KMS, key manager service, encryption 
summary: 利用 Google 的金鑰管理服務來提供第三方金鑰管理服務。 
---
= 利用Google的雲端金鑰管理服務來管理金鑰
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 link:https://cloud.google.com/kms/docs["Google Cloud Platform的金鑰管理服務（雲端KMS）"^] 在ONTAP Google Cloud Platform部署的應用程式中保護您的不加密金鑰。

雲端KMS的金鑰管理可透過CLI或ONTAP REST API啟用。

使用 Cloud KMS 時、請注意、根據預設、會使用 Data SVM 的 LIF 與雲端金鑰管理端點通訊。節點管理網路用於與雲端供應商的驗證服務（oauth2.googleapis.com）進行通訊。如果叢集網路設定不正確、叢集將無法正確使用金鑰管理服務。

.開始之前
* 必須執行9.10.1版或更新版本Cloud Volumes ONTAP
* 已安裝Volume Encryption（VE）授權
* 安裝多租戶加密金鑰管理（MTEKM）授權、從Cloud Volumes ONTAP 版本號為E59.12.1 GA開始。
* 您必須是叢集或SVM管理員
* 現用Google Cloud Platform訂閱


.限制
* 雲端KMS只能在資料SVM上設定




== 組態

.Google Cloud
. 在您的Google Cloud環境中、 link:https://cloud.google.com/kms/docs/creating-keys["建立對稱的GCP金鑰環和金鑰"^]。
. 為Cloud Volumes ONTAP 您的服務帳戶建立自訂角色。
+
[listing]
----
gcloud iam roles create kmsCustomRole
    --project=<project_id>
    --title=<kms_custom_role_name>
    --description=<custom_role_description>
    --permissions=cloudkms.cryptoKeyVersions.get,cloudkms.cryptoKeyVersions.list,cloudkms.cryptoKeyVersions.useToDecrypt,cloudkms.cryptoKeyVersions.useToEncrypt,cloudkms.cryptoKeys.get,cloudkms.keyRings.get,cloudkms.locations.get,cloudkms.locations.list,resourcemanager.projects.get
    --stage=GA
----
. 將自訂角色指派給 Cloud KMS 金鑰和 Cloud Volumes ONTAP 服務帳戶：
`gcloud kms keys add-iam-policy-binding _key_name_ --keyring _key_ring_name_ --location _key_location_ --member serviceAccount:_service_account_Name_ --role projects/_customer_project_id_/roles/kmsCustomRole`
. 下載服務帳戶 JSON 金鑰：
`gcloud iam service-accounts keys create key-file --iam-account=_sa-name_@_project-id_.iam.gserviceaccount.com`


.Cloud Volumes ONTAP
. 使用您偏好的SSH用戶端連線至叢集管理LIF。
. 切換至進階權限層級：
`set -privilege advanced`
. 為資料SVM建立DNS。
`dns create -domains c._<project>_.internal -name-servers _server_address_ -vserver _SVM_name_`
. 建立 CMEK 項目：
`security key-manager external gcp enable -vserver _SVM_name_ -project-id _project_ -key-ring-name _key_ring_name_ -key-ring-location _key_ring_location_ -key-name _key_name_`
. 出現提示時、請從GCP帳戶輸入服務帳戶Json金鑰。
. 確認已啟用的程序成功：
`security key-manager external gcp check -vserver _svm_name_`
. 選用：建立磁碟區以測試加密 `vol create _volume_name_ -aggregate _aggregate_ -vserver _vserver_name_ -size 10G`




== 疑難排解

如果您需要疑難排解、可以跳接上述最後兩個步驟中的原始REST API記錄：

. `set d`
. `systemshell -node _node_ -command tail -f /mroot/etc/log/mlog/kmip2_client.log`

