---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 如何建立附註。 
---
= 使用註釋
:allow-uri-read: 


[role="lead"]
您可以建立附註、並將其指派給監控的資產。附註是提供資產相關資訊的附註、例如實體位置、生命週期結束、儲存層級或Volume服務層級。



== 定義註釋

使用註釋、您可以新增符合業務需求的自訂業務專屬資料至資產。雖然提供一組預設註釋、例如資產生命週期（生日或生命週期結束）、建築物或資料中心位置及層級、但Cloud Insights 您可能會發現想要以其他方式檢視資料。

自訂附註中的資料可補充已收集的裝置資料、例如交換器製造商、連接埠數量和效能統計資料。您使用註釋新增的資料Cloud Insights 不會被任何資訊所發現。

.開始之前
* 列出環境資料必須關聯的任何產業術語。
* 列出環境資料必須關聯的企業術語。
* 找出您可以使用的任何預設註釋類型。
* 找出您需要建立的自訂附註。您必須先建立附註、才能將其指派給資產。


請使用下列步驟建立附註。

.步驟
. 在功能表中、按一下*管理>註釋* Cloud Insights
. 按一下「*+註釋*」以建立新的註釋。
. 輸入新註釋的名稱、說明及類型。
+
例如、輸入下列命令以建立文字附註、定義資料中心4中資產的實體位置：

+
** 輸入註釋的名稱、例如「Location」（位置）
** 輸入註釋內容的說明、例如「實體位置是資料中心4」
** 輸入註釋的「類型」、例如「文字」。






== 手動指派資產附註

指派資產附註有助於您以與業務相關的方式來排序、分組及報告資產。雖然您可以使用註釋規則、自動將註釋指派給特定類型的資產、但您可以使用資產頁面、將註釋指派給個別資產。

.開始之前
* 您必須已建立要指派的附註。


.步驟
. 登入Cloud Insights 您的不執行功能環境。
. 找出您要套用註釋的資產。
+
** 您可以透過查詢、從dashoard小工具中選擇或搜尋來尋找資產。找到您想要的資產後、按一下連結即可開啟資產的登陸頁面。


. 在資產頁面的「使用者資料」區段中、按一下「*+註釋*」。
. 此時會顯示「新增附註」對話方塊。
. 從清單中選取註釋。
. 按一下「Value（值）」、然後根據所選的註釋類型執行下列任一動作：
+
** 如果註釋類型為清單、日期或布林值、請從清單中選取一個值。
** 如果註釋類型為文字、請輸入一個值。


. 按一下「 * 儲存 * 」。


如果您要在指派註釋後變更其值、請按一下註釋欄位、然後選取不同的值。如果註釋屬於清單類型、且已選取「在flly_上新增值」選項、則除了選取現有值之外、您還可以輸入新值。



== 使用註釋規則指派註釋

若要根據您定義的準則自動指派資產附註、請設定附註規則。根據這些規則、將註釋指派給資產。Cloud Insights此外、也提供兩種預設註釋規則、您可以根據需求進行修改、或是在不想使用時加以移除。Cloud Insights



=== 建立註釋規則

您可以使用註釋規則、自動將註釋套用至多個資產、作為手動套用註釋至個別資產的替代方法。Insight評估註釋規則時、在個別資產頁面上手動設定的註釋優先於規則型註釋。

您必須已建立註釋規則的查詢。

雖然您可以在建立規則時編輯註釋類型、但應該事先定義類型。

.步驟
. 按一下*管理>註釋規則*
+
「附註規則」頁面會顯示現有附註規則的清單。

. 按一下「*+ Add*」。
. 請執行下列動作：
+
.. 在*名稱*方塊中、輸入描述規則的唯一名稱。
+
此名稱會顯示在「註釋規則」頁面中。

.. 按一下「*查詢*」、然後選取用來將評註套用至資產的查詢。
.. 按一下*註釋*、然後選取您要套用的註釋。
.. 按一下*值*、然後選取註釋的值。
+
例如、如果您選擇「Birthday」做為註釋、則需指定值的日期。

.. 按一下「*儲存*」
.. 如果您要立即執行所有規則、請按一下*執行所有規則*；否則、規則會以定期排程的時間間隔執行。



