---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: 註冊Cloud Insights 以利執行功能、並創造您的環境。 
---
= NetApp新進人員Cloud Insights
:allow-uri-read: 


[role="lead"]
開始使用Cloud Insights NetApp之前、您必須先在* NetApp Cloud Centr*入口網站上註冊。如果您已經登入NetApp Cloud Central、您可以透過Cloud Insights 幾個快速步驟、開始免費試用版的VMware。


toc::[]


== 建立您的NetApp Cloud Central帳戶

若要註冊以存取NetApp的雲端服務、請前往 https://cloud.netapp.com["* NetApp Cloud Centr*"^] 然後按一下*註冊*。

* 輸入有效的商業電子郵件地址、然後選擇密碼。
* 輸入您的公司名稱和全名。
* 接受條款與條件、然後按一下*註冊*。


接著您將前往NetApp的雲端產品頁面。

選取Cloud Insights 「



=== 如果我已經登入NetApp Cloud、該怎麼辦？

如果您已經擁有NetApp Cloud Central帳戶、只要在上選擇*登入*即可 https://cloud.netapp.com["* NetApp Cloud Centr*"^] 入口網站頁面。

輸入您的電子郵件地址和密碼。接著您將前往NetApp的雲端產品頁面。

選取Cloud Insights 「



== 開始Cloud Insights 免費試用

如果這是您第一次登入Cloud Insights 到此解決方案、請Cloud Insights 在「供應項目」下、按一下「*開始免費試用*」。接著、將會建立貴公司的環境。Cloud Insights

環境建立完成後、您可以使用Cloud Central認證登入Cloud Insights 、並開始免費試用30天的VMware。在本試用版中、您可以探索Cloud Insights 所有的功能。

在免費試用期間、您可以 link:concept_subscribing_to_cloud_insights.html["開始訂購"] 隨時都能Cloud Insights 實現。訂閱後、Cloud Insights 您可以根據目前的訂閱內容來使用功能不完整的功能。



== 登入後立即使用

一旦您的租戶建立完成、您隨時都可以登入NetApp Cloud Portal、然後按一下*移至Cloud Insights *。您將被直接帶到Cloud Insights 您的自然環境中。

您也可以直接開啟瀏覽器至Cloud Insights 您的URL環境、例如：

 https://<environment-name>.c01.cloudinsights.netapp.com/
每位使用者的邀請電子郵件中也會包含此URL、方便您輕鬆存取及加入書籤。如果使用者尚未登入Cloud Central、系統會提示他們登入。


NOTE: 新使用者仍必須先註冊以存取Cloud Central、才能存取其環境URL。

第一次登入新環境時、系統會引導您完成設定 link:task_getting_started_with_cloud_insights.html["*開始收集資料*"]。



== 登出

若要登出Cloud Insights 此功能、請按一下您的*使用者名稱*、然後選取*登出*。系統會將您帶回Cloud Central登入畫面。


NOTE: 登出Cloud Insights 功能可讓您登出Cloud Central。您也會登出使用Cloud Central登入的其他NetApp Cloud服務。
