---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: 資料收集器ONTAP 
---
= NetApp ONTAP 數據管理軟體資料收集器
:allow-uri-read: 


[role="lead"]
此資料收集器會使用ONTAP 隻讀API呼叫ONTAP 來自執行VMware的儲存系統、從該帳戶取得庫存和效能資料。此資料收集器也會在叢集應用程式登錄中建立記錄、以加速支援。



== 術語

從VMware資料收集器取得庫存與效能資料。Cloud Insights ONTAP對於所取得的每種資產類型、都會顯示該資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | 詞彙Cloud Insights 


| 磁碟 | 磁碟 


| RAID群組 | 磁碟群組 


| 叢集 | 儲存設備 


| 節點 | 儲存節點 


| Aggregate | 儲存資源池 


| LUN | Volume 


| Volume | 內部Volume 
|===


== 資料管理術語ONTAP

下列詞彙適用於ONTAP 您在《支援資料管理》儲存資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。



=== 儲存設備

* 模型–此叢集內唯一、獨立節點模型名稱的以逗號分隔的清單。如果叢集內的所有節點都是相同的模型類型、則只會顯示一個模型名稱。
* 廠商–如果您要設定新的資料來源、您會看到相同的廠商名稱。
* 序號–陣列序號。在叢集架構儲存系統（例如ONTAP 、《資料管理》）中、此序號可能不如個別的「儲存節點」序號所使用。
* IP–通常是在資料來源中設定的IP或主機名稱。
* 微碼版本–韌體。
* 原始容量：系統中所有實體磁碟的基礎2總和、無論其角色為何。
* 延遲：代表主機面對的工作負載在讀取和寫入過程中所經歷的情況。理想的情況Cloud Insights 是、這個價值是直接來源於此、但這種情況通常並非如此。代替陣列提供此功能、Cloud Insights 往往會執行IOP加權計算、以個別內部磁碟區的統計資料為基礎。
* 處理量：從內部磁碟區集合而來。管理：這可能包含裝置管理介面的超連結。以程式設計的方式、由Cloud Insights 來源資料來源建立、作為庫存報告的一部分。




=== 儲存資源池

* 儲存設備：此資源池所使用的儲存陣列。必填。
* 類型–從列舉的可能性清單清單中選取一個描述性值。最常見的是「Aggregate」或「RAID Group」。
* 節點–如果此儲存陣列的架構使集區屬於特定儲存節點、則其名稱將會顯示在這裡、以超連結的形式連結至其自己的登陸頁面。
* 使用Flash Pool–是/否值–此SATA / SAS型集區是否使用SSD進行快取加速？
* 備援：RAID層級或保護方案。RAID-DP為雙同位元檢查、RAID_tp為三同位元檢查。
* 容量：此處的值是已用邏輯容量、可用容量和邏輯總容量、以及這些容量使用的百分比。
* 過度委派容量：如果使用效率技術、您已將容量或內部Volume容量的總和分配給大於儲存資源池邏輯容量的總和、則此處的百分比值將大於0%。
* Snapshot–已使用的快照容量和總容量、如果您的儲存資源池架構將部分容量專用於專為快照而設計的區段區域。在不支援支援的情況下、支援的部分可能會出現這個問題、而其他的不支援的組態則較少。ONTAP MetroCluster ONTAP
* 使用率–百分比值、顯示此儲存資源池中任何磁碟貢獻容量的最高磁碟使用率百分比。磁碟使用率不一定與陣列效能有密切的關聯、因為磁碟重建、重複資料刪除活動等原因、在缺乏主機驅動的工作負載的情況下、使用率可能會很高。此外、許多陣列的複寫實作可能會提高磁碟使用率、但不會顯示為內部磁碟區或磁碟區工作負載。
* IOPS：所有磁碟的IOPs總和、可為此儲存資源池提供容量。處理量：所有磁碟的總處理量、可為此儲存資源池提供容量。




=== 儲存節點

* 儲存設備：此節點屬於何種儲存陣列。必填。
* HA合作夥伴：在節點將容錯移轉至一個節點、而只有一個節點的平台上、通常會顯示於此處。
* 狀態–節點健全狀況。只有當陣列健全狀況足以由資料來源進行庫存時、才能使用。
* 模型–節點的模型名稱。
* 版本–裝置的版本名稱。
* 序號–節點序號。
* 記憶體：基礎2記憶體（若有）。
* 使用率：ONTAP 在功能方面、這是專屬演算法的控制器壓力索引。每次效能意見調查都會報告0到100%之間的數字、這是WAFL 指較高的VMware磁碟爭用或平均CPU使用率。如果您觀察到持續值> 50%、這表示規模過小–可能是控制器/節點不夠大、或旋轉磁碟不足以吸收寫入工作負載。
* IOPS–直接衍生自ONTAP 節點物件上的RzAPI呼叫。
* 延遲：直接衍生自ONTAP 節點物件上的RzAPI呼叫。
* 處理量：直接衍生自ONTAP 節點物件上的R叢 集ZAPI呼叫。
* 處理器–CPU數。




== 需求

以下是設定及使用此資料收集器的需求：

* 您必須擁有設定為唯讀API呼叫的管理員帳戶存取權。
* 帳戶詳細資料包括使用者名稱和密碼。
* 連接埠需求：80或443
* 帳戶權限：
+
** 將OnTapi應用程式的唯讀角色名稱設為預設Vserver
** 您可能需要額外的選擇性寫入權限。請參閱下方「權限相關注意事項」。


* 不含授權要求：ONTAP
+
** 用於光纖通道探索的FCP授權和對應/遮罩磁碟區






== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| NetApp管理IP | NetApp叢集的IP位址或完整網域名稱 


| 使用者名稱 | NetApp叢集的使用者名稱 


| 密碼 | NetApp叢集的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 連線類型 | 選擇HTTP（預設連接埠80）或HTTPS（預設連接埠443）。預設值為HTTPS 


| 置換通訊連接埠 | 如果不想使用預設值、請指定不同的連接埠 


| 庫存輪詢時間間隔（分鐘） | 預設為60分鐘。 


| 用於TLS for HTTPS | 使用HTTPS時、僅允許TLS做為傳輸協定 


| 自動查詢網路群組 | 啟用匯出原則規則的自動網路群組查詢 


| 網路群組擴充 | 網路群組擴充策略：選擇_file_或_Shell。預設值為_Shell。 


| HTTP讀取逾時秒數 | 預設值為30 


| 強制回應為utf-8 | 強制資料收集器程式碼將CLI的回應解譯為UTF-8 


| 效能意見調查時間間隔（秒） | 預設值為900秒。 


| 進階計數器資料收集 | 實現ONTAP 整合。選取此選項可在ONTAP 輪詢中包含「功能先進的計數器」資料。從清單中選擇所需的計數器。 
|===


== 權限相關注意事項

由於Cloud Insights 許多功能不均ONTAP 的儀表板都仰賴進階ONTAP 的功能表、因此您必須在資料收集器進階組態區段中啟用*進階計數器資料收集*。

您也應該確保ONTAP 已啟用對該API的寫入權限。這通常需要具有必要權限的叢集層級帳戶。

若要在Cloud Insights 叢集層級建立一個用於執行故障的本機帳戶、ONTAP 請使用叢集管理管理員使用者名稱/密碼登入到故障碼、然後在ONTAP 故障碼伺服器上執行下列命令：

. 使用下列命令建立唯讀角色。
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname “cluster application-record create”
....
. 使用下列命令建立唯讀使用者。執行create命令後、系統會提示您輸入此使用者的密碼。
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


如果使用AD/LDAP帳戶、則命令應該是

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
產生的角色和使用者登入內容如下：

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1::security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....


== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：



==== 庫存

[cols="2*"]
|===
| 問題： | 試用： 


| 接收401 HTTP回應或13003 ZAPI錯誤代碼、且ZAPI傳回「權限不足」或「未授權使用此命令」 | 檢查使用者名稱和密碼、以及使用者權限/權限。 


| 叢集版本低於8.1 | 叢集支援的最低版本為8.1。升級至支援的最低版本。 


| ZAPI傳回「叢集角色不是叢集管理LIF」 | AU需要與叢集管理IP對話。檢查IP並視需要變更為不同的IP 


| 錯誤：「不支援7模式檔案管理器」 | 如果您使用此資料收集器來探索7模式檔案管理器、就可能發生這種情況。改為將IP變更為指向cDOT叢集。 


| ZAPI命令在重試後失敗 | AU與叢集發生通訊問題。檢查網路、連接埠號碼和IP位址。使用者也應該嘗試從AU機器的命令列執行命令。 


| AU無法透過HTTP連線至ZAPI | 檢查ZAPI連接埠是否接受純文字。如果AU嘗試傳送純文字到SSL通訊端、通訊就會失敗。 


| 通訊失敗、出現SSLException | AU正在嘗試將SSL傳送至檔案管理器上的純文字連接埠。檢查ZAPI連接埠是否接受SSL、或使用不同的連接埠。 


| 其他連線錯誤：ZAPI回應的錯誤代碼為13001、「資料庫未開啟」ZAPI錯誤代碼為60、回應包含「API未按時完成」ZAPI回應包含「initialize_session（）傳回的空環境」ZAPI錯誤代碼為14007、回應包含「節點不健全」 | 檢查網路、連接埠號碼和IP位址。使用者也應該嘗試從AU機器的命令列執行命令。 
|===


==== 效能

[cols="2*"]
|===
| 問題： | 試用： 


| 「無法從ZAPI收集效能」錯誤 | 這通常是因為perf stat未執行。請在每個節點上嘗試下列命令：>_system nodesystem shell -node*-command「spemtl -h cmd–stop；spemtl -h cmd–exec__」 
|===
如需其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["資料收集器支援對照表"]。
