---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: 適用於NetApp ONTAP 的Amazon FSX資料蒐集器 
---
= 適用於NetApp ONTAP 的Amazon FSX資料收集器
:allow-uri-read: 


[role="lead"]
此資料收集器會從Amazon FSX for NetApp ONTAP 獲取庫存與效能資料。此資料收集器將逐步提供給Cloud Insights 整個「穩定」服務區域。如果Cloud Insights 您在自己的《不景》中沒有看到此收藏器的圖示、請聯絡您的銷售人員。



== 術語

從FSx-NetApp資料收集器取得庫存與效能資料。Cloud Insights對於所取得的每種資產類型、都會顯示該資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | 詞彙Cloud Insights 


| 叢集 | 儲存設備 


| LUN | Volume 


| Volume | 內部Volume 
|===


== FSx-NetApp術語

以下術語適用於您在FSx-NetApp儲存資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。



=== 儲存設備

* 模型–此叢集中唯一、獨立模型名稱的以逗號分隔的清單。
* 廠商：AWS
* 序號–陣列序號。
* IP–通常是在資料來源中設定的IP或主機名稱。
* 原始容量：系統中所有實體磁碟的基礎2總和、無論其角色為何。
* 延遲：代表主機面對的工作負載在讀取和寫入過程中所經歷的情況。理想的情況Cloud Insights 是、這個價值是直接來源於此、但這種情況通常並非如此。代替陣列提供此功能、Cloud Insights 往往會執行IOP加權計算、以個別內部磁碟區的統計資料為基礎。
* 處理量：從內部磁碟區集合而來。管理：這可能包含裝置管理介面的超連結。以程式設計的方式、由Cloud Insights 來源資料來源建立、作為庫存報告的一部分。




=== 儲存資源池

* 儲存設備：此資源池所使用的儲存陣列。必填。
* 類型–從列舉的可能性清單清單中選取一個描述性值。最常見的是「Aggregate」或「RAID Group」。
* 使用Flash Pool–是/否值–此SATA / SAS型集區是否使用SSD進行快取加速？
* 備援：RAID層級或保護方案。RAID-DP為雙同位元檢查、RAID_tp為三同位元檢查。
* 容量：此處的值是已用邏輯容量、可用容量和邏輯總容量、以及這些容量使用的百分比。
* 過度委派容量：如果使用效率技術、您已將容量或內部Volume容量的總和分配給大於儲存資源池邏輯容量的總和、則此處的百分比值將大於0%。
* Snapshot–已使用的快照容量和總容量、如果您的儲存資源池架構將部分容量專用於專為快照而設計的區段區域。在不支援支援的情況下、支援的部分可能會出現這個問題、而其他的不支援的組態則較少。ONTAP MetroCluster ONTAP
* 使用率–百分比值、顯示此儲存資源池中任何磁碟貢獻容量的最高磁碟使用率百分比。磁碟使用率不一定與陣列效能有密切的關聯、因為磁碟重建、重複資料刪除活動等原因、在缺乏主機驅動的工作負載的情況下、使用率可能會很高。此外、許多陣列的複寫實作可能會提高磁碟使用率、但不會顯示為內部磁碟區或磁碟區工作負載。
* IOPS：所有磁碟的IOPs總和、可為此儲存資源池提供容量。處理量：所有磁碟的總處理量、可為此儲存資源池提供容量。




== 需求

以下是設定及使用此資料收集器的需求：

* 您必須擁有設定為唯讀API呼叫的管理員帳戶存取權。
* 帳戶詳細資料包括使用者名稱和密碼。
* 連接埠需求：80或443




== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| NetApp管理IP | NetApp叢集的IP位址或完整網域名稱 


| 使用者名稱 | NetApp叢集的使用者名稱 


| 密碼 | NetApp叢集的密碼 
|===


== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：



==== 庫存

[cols="2*"]
|===
| 問題： | 試用： 


| 接收401 HTTP回應或13003 ZAPI錯誤代碼、且ZAPI傳回「權限不足」或「未授權使用此命令」 | 檢查使用者名稱和密碼、以及使用者權限/權限。 


| ZAPI傳回「叢集角色不是叢集管理LIF」 | AU需要與叢集管理IP對話。檢查IP並視需要變更為不同的IP 


| ZAPI命令在重試後失敗 | AU與叢集發生通訊問題。檢查網路、連接埠號碼和IP位址。使用者也應該嘗試從AU機器的命令列執行命令。 


| AU無法透過HTTP連線至ZAPI | 檢查ZAPI連接埠是否接受純文字。如果AU嘗試傳送純文字到SSL通訊端、通訊就會失敗。 


| 通訊失敗、出現SSLException | AU正在嘗試將SSL傳送至檔案管理器上的純文字連接埠。檢查ZAPI連接埠是否接受SSL、或使用不同的連接埠。 


| 其他連線錯誤：ZAPI回應的錯誤代碼為13001、「資料庫未開啟」ZAPI錯誤代碼為60、回應包含「API未按時完成」ZAPI回應包含「initialize_session（）傳回的空環境」ZAPI錯誤代碼為14007、回應包含「節點不健全」 | 檢查網路、連接埠號碼和IP位址。使用者也應該嘗試從AU機器的命令列執行命令。 
|===
如需其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["資料收集器支援對照表"]。
